//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerSite()
        {
            this.CustomerContactPersons = new HashSet<CustomerContactPerson>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid CustomerID { get; set; }
        public string CustomerSiteID { get; set; }
        public string CustomerSiteName1 { get; set; }
        public string CustomerSiteName2 { get; set; }
        public string CustomerSiteName3 { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public Nullable<System.Guid> DistrictID { get; set; }
        public string TelNo { get; set; }
        public string TelExtNo { get; set; }
        public string FaxNo { get; set; }
        public string FaxExtNo { get; set; }
        public string WebSiteAddress { get; set; }
        public string FTPSiteAddress { get; set; }
        public System.Guid CustomerSiteStatus { get; set; }
        public string CustomerSiteRemark { get; set; }
        public string Language { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        public virtual InfoFabCode InfoFabCode { get; set; }
        public virtual InfoFabDistrict InfoFabDistrict { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactPerson> CustomerContactPersons { get; set; }
    }
}
