//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public System.DateTime PostTime { get; set; }
        public string EventType { get; set; }
        public string ServerName { get; set; }
        public string LoginName { get; set; }
        public string UserName { get; set; }
        public string DatabaseName { get; set; }
        public string SchemaName { get; set; }
        public string ObjectName { get; set; }
        public string ObjectType { get; set; }
        public string TSQLCommand { get; set; }
        public string CommandText { get; set; }
    }
}
