//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iKGDBEntities : DbContext
    {
        public iKGDBEntities()
            : base("name=iKGDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InfoFabAnnualLeave> InfoFabAnnualLeaves { get; set; }
        public virtual DbSet<InfoFabAnnualLeaveCondition> InfoFabAnnualLeaveConditions { get; set; }
        public virtual DbSet<InfoFabAttnEnv> InfoFabAttnEnvs { get; set; }
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<InfoFabArea> InfoFabAreas { get; set; }
        public virtual DbSet<InfoFabCatContent> InfoFabCatContents { get; set; }
        public virtual DbSet<InfoFabCategory> InfoFabCategories { get; set; }
        public virtual DbSet<InfoFabClass> InfoFabClasses { get; set; }
        public virtual DbSet<InfoFabCode> InfoFabCodes { get; set; }
        public virtual DbSet<InfoFabColumn> InfoFabColumns { get; set; }
        public virtual DbSet<InfoFabColumnsSetting> InfoFabColumnsSettings { get; set; }
        public virtual DbSet<InfoFabContent> InfoFabContents { get; set; }
        public virtual DbSet<InfoFabDistrict> InfoFabDistricts { get; set; }
        public virtual DbSet<InfoFabEmpDeputy> InfoFabEmpDeputies { get; set; }
        public virtual DbSet<InfoFabEmployee> InfoFabEmployees { get; set; }
        public virtual DbSet<InfoFabEmpOrg> InfoFabEmpOrgs { get; set; }
        public virtual DbSet<InfoFabEmpProCert> InfoFabEmpProCerts { get; set; }
        public virtual DbSet<InfoFabENV> InfoFabENVs { get; set; }
        public virtual DbSet<InfoFabENVItem> InfoFabENVItems { get; set; }
        public virtual DbSet<InfoFabForgotPWD> InfoFabForgotPWDs { get; set; }
        public virtual DbSet<InfoFabLangMapping> InfoFabLangMappings { get; set; }
        public virtual DbSet<InfoFabMessage> InfoFabMessages { get; set; }
        public virtual DbSet<InfoFabMessageContent> InfoFabMessageContents { get; set; }
        public virtual DbSet<InfoFabNotify> InfoFabNotifies { get; set; }
        public virtual DbSet<InfoFabOrganization> InfoFabOrganizations { get; set; }
        public virtual DbSet<InfoFabOrgEnv> InfoFabOrgEnvs { get; set; }
        public virtual DbSet<InfoFabPersonal> InfoFabPersonals { get; set; }
        public virtual DbSet<InfoFabProCert> InfoFabProCerts { get; set; }
        public virtual DbSet<InfoFabProject> InfoFabProjects { get; set; }
        public virtual DbSet<InfoFabProjectAttendee> InfoFabProjectAttendees { get; set; }
        public virtual DbSet<InfoFabProjectClass> InfoFabProjectClasses { get; set; }
        public virtual DbSet<InfoFabProjectNode> InfoFabProjectNodes { get; set; }
        public virtual DbSet<InfoFabRole> InfoFabRoles { get; set; }
        public virtual DbSet<InfoFabRoleAuth> InfoFabRoleAuths { get; set; }
        public virtual DbSet<InfoFabRoleUser> InfoFabRoleUsers { get; set; }
        public virtual DbSet<InfoFabTable> InfoFabTables { get; set; }
        public virtual DbSet<InfoFabType> InfoFabTypes { get; set; }
        public virtual DbSet<InfoFabUser> InfoFabUsers { get; set; }
        public virtual DbSet<InfoFabUserAuth> InfoFabUserAuths { get; set; }
        public virtual DbSet<InfoFabWFForm> InfoFabWFForms { get; set; }
        public virtual DbSet<InfoFabWFProjectTest> InfoFabWFProjectTests { get; set; }
        public virtual DbSet<InfoFabWFProjectTestHistory> InfoFabWFProjectTestHistories { get; set; }
        public virtual DbSet<InfoFabWFScheme> InfoFabWFSchemes { get; set; }
        public virtual DbSet<InfoFabWFSchemeHistory> InfoFabWFSchemeHistories { get; set; }
        public virtual DbSet<SampleDataTable> SampleDataTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WorkflowGlobalParameter> WorkflowGlobalParameters { get; set; }
        public virtual DbSet<WorkflowInbox> WorkflowInboxes { get; set; }
        public virtual DbSet<WorkflowProcessInstance> WorkflowProcessInstances { get; set; }
        public virtual DbSet<WorkflowProcessInstancePersistence> WorkflowProcessInstancePersistences { get; set; }
        public virtual DbSet<WorkflowProcessInstanceStatu> WorkflowProcessInstanceStatus { get; set; }
        public virtual DbSet<WorkflowProcessScheme> WorkflowProcessSchemes { get; set; }
        public virtual DbSet<WorkflowProcessTimer> WorkflowProcessTimers { get; set; }
        public virtual DbSet<WorkflowProcessTransitionHistory> WorkflowProcessTransitionHistories { get; set; }
        public virtual DbSet<WorkflowRuntime> WorkflowRuntimes { get; set; }
        public virtual DbSet<WorkflowScheme> WorkflowSchemes { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Catalog> Catalogs { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RefProductCatalog> RefProductCatalogs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerBusinessPartner> CustomerBusinessPartners { get; set; }
        public virtual DbSet<CustomerBusinessType> CustomerBusinessTypes { get; set; }
        public virtual DbSet<CustomerContactOwner> CustomerContactOwners { get; set; }
        public virtual DbSet<CustomerContactPerson> CustomerContactPersons { get; set; }
        public virtual DbSet<CustomerCreditLimit> CustomerCreditLimits { get; set; }
        public virtual DbSet<CustomerDelayPayment> CustomerDelayPayments { get; set; }
        public virtual DbSet<CustomerMonthlySalesAmount> CustomerMonthlySalesAmounts { get; set; }
        public virtual DbSet<CustomerOutsourceAmount> CustomerOutsourceAmounts { get; set; }
        public virtual DbSet<CustomerProductType> CustomerProductTypes { get; set; }
        public virtual DbSet<CustomerSalesAmount> CustomerSalesAmounts { get; set; }
        public virtual DbSet<CustomerSalesProductType> CustomerSalesProductTypes { get; set; }
        public virtual DbSet<CustomerSite> CustomerSites { get; set; }
        public virtual DbSet<DistributionChannel> DistributionChannels { get; set; }
        public virtual DbSet<PartClass> PartClasses { get; set; }
        public virtual DbSet<PartLovCode> PartLovCodes { get; set; }
        public virtual DbSet<PartLovKind> PartLovKinds { get; set; }
        public virtual DbSet<PartLovType> PartLovTypes { get; set; }
        public virtual DbSet<PartSerialNoRule> PartSerialNoRules { get; set; }
        public virtual DbSet<PartType> PartTypes { get; set; }
        public virtual DbSet<PartTypeClass> PartTypeClasses { get; set; }
        public virtual DbSet<PartTypeMaterialModel> PartTypeMaterialModels { get; set; }
        public virtual DbSet<PartTypeSerialNo> PartTypeSerialNoes { get; set; }
        public virtual DbSet<SalesArea> SalesAreas { get; set; }
        public virtual DbSet<SalesOrganization> SalesOrganizations { get; set; }
        public virtual DbSet<InfoFabEmpLeave> InfoFabEmpLeaves { get; set; }
        public virtual DbSet<InfoFabEmpLeaveDay> InfoFabEmpLeaveDays { get; set; }
        public virtual DbSet<InfoFabEmpOvertime> InfoFabEmpOvertimes { get; set; }
        public virtual DbSet<InfoFabEmpProcEff> InfoFabEmpProcEffs { get; set; }
        public virtual DbSet<InfoFabEmpSkill> InfoFabEmpSkills { get; set; }
        public virtual DbSet<InfoFabEmpSkillClass> InfoFabEmpSkillClasses { get; set; }
        public virtual DbSet<InfoFabEmpTaskAssign> InfoFabEmpTaskAssigns { get; set; }
        public virtual DbSet<InfoFabEmpTaskDailyRecord> InfoFabEmpTaskDailyRecords { get; set; }
        public virtual DbSet<InfoFabLeaveCode> InfoFabLeaveCodes { get; set; }
        public virtual DbSet<InfoFabOffDay> InfoFabOffDays { get; set; }
        public virtual DbSet<InfoFabOvertimeCode> InfoFabOvertimeCodes { get; set; }
        public virtual DbSet<InfoFabPayControl> InfoFabPayControls { get; set; }
        public virtual DbSet<InfoFabPayPeriod> InfoFabPayPeriods { get; set; }
        public virtual DbSet<InfoFabProcedure> InfoFabProcedures { get; set; }
        public virtual DbSet<InfoFabProCertSkill> InfoFabProCertSkills { get; set; }
        public virtual DbSet<InfoFabSkill> InfoFabSkills { get; set; }
        public virtual DbSet<InfoFabSkillType> InfoFabSkillTypes { get; set; }
        public virtual DbSet<InfoFabTask> InfoFabTasks { get; set; }
        public virtual DbSet<InfoFabTaskDetail> InfoFabTaskDetails { get; set; }
        public virtual DbSet<InfoFabTaskEnv> InfoFabTaskEnvs { get; set; }
        public virtual DbSet<InfoFabTaskKind> InfoFabTaskKinds { get; set; }
        public virtual DbSet<InfoFabTaskProcedure> InfoFabTaskProcedures { get; set; }
        public virtual DbSet<InfoFabTaskProject> InfoFabTaskProjects { get; set; }
        public virtual DbSet<InfoFabTaskProperty> InfoFabTaskProperties { get; set; }
        public virtual DbSet<InfoFabTaskPropTemplate> InfoFabTaskPropTemplates { get; set; }
        public virtual DbSet<InfoFabWorkCode> InfoFabWorkCodes { get; set; }
        public virtual DbSet<InfoFabWorkGroup> InfoFabWorkGroups { get; set; }
        public virtual DbSet<InfoFabWorkPattern> InfoFabWorkPatterns { get; set; }
        public virtual DbSet<JJMFEmpProcedure> JJMFEmpProcedures { get; set; }
        public virtual DbSet<JJMFEmpTaskDailyDisplay> JJMFEmpTaskDailyDisplays { get; set; }
        public virtual DbSet<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords { get; set; }
        public virtual DbSet<JJMFProcedure> JJMFProcedures { get; set; }
        public virtual DbSet<JJMFTask> JJMFTasks { get; set; }
        public virtual DbSet<JJMFTaskCal> JJMFTaskCals { get; set; }
        public virtual DbSet<JJMFTaskCalItem> JJMFTaskCalItems { get; set; }
    }
}
