//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabWorkCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabWorkCode()
        {
            this.InfoFabEmpLeaves = new HashSet<InfoFabEmpLeave>();
            this.InfoFabEmpLeaveDays = new HashSet<InfoFabEmpLeaveDay>();
            this.InfoFabEmpOvertimes = new HashSet<InfoFabEmpOvertime>();
            this.InfoFabEmpTaskDailyRecords = new HashSet<InfoFabEmpTaskDailyRecord>();
            this.InfoFabWorkPatterns = new HashSet<InfoFabWorkPattern>();
            this.JJMFEmpTaskDailyRecords = new HashSet<JJMFEmpTaskDailyRecord>();
        }
    
        public System.Guid ID { get; set; }
        public string WorkCode { get; set; }
        public string WorkCodeName { get; set; }
        public Nullable<System.TimeSpan> WorkStarttTime { get; set; }
        public Nullable<System.TimeSpan> WorkEndTime { get; set; }
        public Nullable<bool> IsCrossDay { get; set; }
        public Nullable<System.TimeSpan> LunchStartTime { get; set; }
        public Nullable<System.TimeSpan> LunchEndTime { get; set; }
        public Nullable<System.TimeSpan> DinnerTime { get; set; }
        public Nullable<System.TimeSpan> DinnerEndTime { get; set; }
        public Nullable<System.TimeSpan> SnackStartTime { get; set; }
        public Nullable<System.TimeSpan> SnackEndTime { get; set; }
        public Nullable<System.TimeSpan> OffStartTime1 { get; set; }
        public Nullable<System.TimeSpan> OffEndTime1 { get; set; }
        public Nullable<System.TimeSpan> OffStartTime2 { get; set; }
        public Nullable<System.TimeSpan> OffEndTime2 { get; set; }
        public Nullable<System.TimeSpan> OffStartTime3 { get; set; }
        public Nullable<System.TimeSpan> OffEndTime3 { get; set; }
        public Nullable<System.TimeSpan> OffStartTime4 { get; set; }
        public Nullable<System.TimeSpan> OffEndTime4 { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeave> InfoFabEmpLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeaveDay> InfoFabEmpLeaveDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOvertime> InfoFabEmpOvertimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpTaskDailyRecord> InfoFabEmpTaskDailyRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkPattern> InfoFabWorkPatterns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords { get; set; }
    }
}
