//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabEmployee()
        {
            this.InfoFabEmpOrgs = new HashSet<InfoFabEmpOrg>();
            this.InfoFabEmpSkills = new HashSet<InfoFabEmpSkill>();
            this.JJMFEmpProcedures = new HashSet<JJMFEmpProcedure>();
            this.JJMFEmpTaskDailyDisplays = new HashSet<JJMFEmpTaskDailyDisplay>();
            this.JJMFEmpTaskDailyRecords = new HashSet<JJMFEmpTaskDailyRecord>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid PersonalID { get; set; }
        public string EmpNo { get; set; }
        public System.Guid JobKindID { get; set; }
        public System.Guid PayType { get; set; }
        public System.DateTime OnBoardDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public System.Guid Status { get; set; }
        public string PictureImage { get; set; }
        public Nullable<System.Guid> WageRank { get; set; }
        public string Remark { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        public virtual InfoFabCode InfoFabCode { get; set; }
        public virtual InfoFabCode InfoFabCode1 { get; set; }
        public virtual InfoFabCode InfoFabCode2 { get; set; }
        public virtual InfoFabCode InfoFabCode3 { get; set; }
        public virtual InfoFabPersonal InfoFabPersonal { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOrg> InfoFabEmpOrgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpSkill> InfoFabEmpSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpProcedure> JJMFEmpProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyDisplay> JJMFEmpTaskDailyDisplays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords { get; set; }
    }
}
