//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabUser()
        {
            this.InfoFabAnnualLeaves = new HashSet<InfoFabAnnualLeave>();
            this.InfoFabAnnualLeaves1 = new HashSet<InfoFabAnnualLeave>();
            this.InfoFabAnnualLeaveConditions = new HashSet<InfoFabAnnualLeaveCondition>();
            this.InfoFabAnnualLeaveConditions1 = new HashSet<InfoFabAnnualLeaveCondition>();
            this.InfoFabAttnEnvs = new HashSet<InfoFabAttnEnv>();
            this.InfoFabAttnEnvs1 = new HashSet<InfoFabAttnEnv>();
            this.InfoFabAreas = new HashSet<InfoFabArea>();
            this.InfoFabAreas1 = new HashSet<InfoFabArea>();
            this.InfoFabCatContents = new HashSet<InfoFabCatContent>();
            this.InfoFabCatContents1 = new HashSet<InfoFabCatContent>();
            this.InfoFabCategories = new HashSet<InfoFabCategory>();
            this.InfoFabCategories1 = new HashSet<InfoFabCategory>();
            this.InfoFabClasses = new HashSet<InfoFabClass>();
            this.InfoFabClasses1 = new HashSet<InfoFabClass>();
            this.InfoFabCodes = new HashSet<InfoFabCode>();
            this.InfoFabCodes1 = new HashSet<InfoFabCode>();
            this.InfoFabColumns = new HashSet<InfoFabColumn>();
            this.InfoFabColumns1 = new HashSet<InfoFabColumn>();
            this.InfoFabColumnsSettings = new HashSet<InfoFabColumnsSetting>();
            this.InfoFabColumnsSettings1 = new HashSet<InfoFabColumnsSetting>();
            this.InfoFabContents = new HashSet<InfoFabContent>();
            this.InfoFabContents1 = new HashSet<InfoFabContent>();
            this.InfoFabContents2 = new HashSet<InfoFabContent>();
            this.InfoFabDistricts = new HashSet<InfoFabDistrict>();
            this.InfoFabDistricts1 = new HashSet<InfoFabDistrict>();
            this.InfoFabEmpDeputies = new HashSet<InfoFabEmpDeputy>();
            this.InfoFabEmpDeputies1 = new HashSet<InfoFabEmpDeputy>();
            this.InfoFabEmployees = new HashSet<InfoFabEmployee>();
            this.InfoFabEmployees1 = new HashSet<InfoFabEmployee>();
            this.InfoFabEmpOrgs = new HashSet<InfoFabEmpOrg>();
            this.InfoFabEmpOrgs1 = new HashSet<InfoFabEmpOrg>();
            this.InfoFabEmpProCerts = new HashSet<InfoFabEmpProCert>();
            this.InfoFabEmpProCerts1 = new HashSet<InfoFabEmpProCert>();
            this.InfoFabENVs = new HashSet<InfoFabENV>();
            this.InfoFabENVs1 = new HashSet<InfoFabENV>();
            this.InfoFabENVItems = new HashSet<InfoFabENVItem>();
            this.InfoFabENVItems1 = new HashSet<InfoFabENVItem>();
            this.InfoFabForgotPWDs = new HashSet<InfoFabForgotPWD>();
            this.InfoFabForgotPWDs1 = new HashSet<InfoFabForgotPWD>();
            this.InfoFabLangMappings = new HashSet<InfoFabLangMapping>();
            this.InfoFabLangMappings1 = new HashSet<InfoFabLangMapping>();
            this.InfoFabMessages = new HashSet<InfoFabMessage>();
            this.InfoFabMessages1 = new HashSet<InfoFabMessage>();
            this.InfoFabMessageContents = new HashSet<InfoFabMessageContent>();
            this.InfoFabMessageContents1 = new HashSet<InfoFabMessageContent>();
            this.InfoFabNotifies = new HashSet<InfoFabNotify>();
            this.InfoFabNotifies1 = new HashSet<InfoFabNotify>();
            this.InfoFabNotifies2 = new HashSet<InfoFabNotify>();
            this.InfoFabOrganizations = new HashSet<InfoFabOrganization>();
            this.InfoFabOrganizations1 = new HashSet<InfoFabOrganization>();
            this.InfoFabOrgEnvs = new HashSet<InfoFabOrgEnv>();
            this.InfoFabOrgEnvs1 = new HashSet<InfoFabOrgEnv>();
            this.InfoFabPersonals = new HashSet<InfoFabPersonal>();
            this.InfoFabPersonals1 = new HashSet<InfoFabPersonal>();
            this.InfoFabProCerts = new HashSet<InfoFabProCert>();
            this.InfoFabProCerts1 = new HashSet<InfoFabProCert>();
            this.InfoFabProjects = new HashSet<InfoFabProject>();
            this.InfoFabProjects1 = new HashSet<InfoFabProject>();
            this.InfoFabProjects2 = new HashSet<InfoFabProject>();
            this.InfoFabProjectAttendees = new HashSet<InfoFabProjectAttendee>();
            this.InfoFabProjectAttendees1 = new HashSet<InfoFabProjectAttendee>();
            this.InfoFabProjectAttendees2 = new HashSet<InfoFabProjectAttendee>();
            this.InfoFabProjectClasses = new HashSet<InfoFabProjectClass>();
            this.InfoFabProjectClasses1 = new HashSet<InfoFabProjectClass>();
            this.InfoFabProjectNodes = new HashSet<InfoFabProjectNode>();
            this.InfoFabProjectNodes1 = new HashSet<InfoFabProjectNode>();
            this.InfoFabRoles = new HashSet<InfoFabRole>();
            this.InfoFabRoles1 = new HashSet<InfoFabRole>();
            this.InfoFabRoleAuths = new HashSet<InfoFabRoleAuth>();
            this.InfoFabRoleAuths1 = new HashSet<InfoFabRoleAuth>();
            this.InfoFabRoleUsers = new HashSet<InfoFabRoleUser>();
            this.InfoFabRoleUsers1 = new HashSet<InfoFabRoleUser>();
            this.InfoFabRoleUsers2 = new HashSet<InfoFabRoleUser>();
            this.InfoFabTables = new HashSet<InfoFabTable>();
            this.InfoFabTables1 = new HashSet<InfoFabTable>();
            this.InfoFabTypes = new HashSet<InfoFabType>();
            this.InfoFabTypes1 = new HashSet<InfoFabType>();
            this.Customers = new HashSet<Customer>();
            this.Customers1 = new HashSet<Customer>();
            this.CustomerBusinessPartners = new HashSet<CustomerBusinessPartner>();
            this.CustomerBusinessPartners1 = new HashSet<CustomerBusinessPartner>();
            this.CustomerBusinessTypes = new HashSet<CustomerBusinessType>();
            this.CustomerBusinessTypes1 = new HashSet<CustomerBusinessType>();
            this.CustomerContactOwners = new HashSet<CustomerContactOwner>();
            this.CustomerContactOwners1 = new HashSet<CustomerContactOwner>();
            this.CustomerContactPersons = new HashSet<CustomerContactPerson>();
            this.CustomerContactPersons1 = new HashSet<CustomerContactPerson>();
            this.CustomerCreditLimits = new HashSet<CustomerCreditLimit>();
            this.CustomerCreditLimits1 = new HashSet<CustomerCreditLimit>();
            this.CustomerDelayPayments = new HashSet<CustomerDelayPayment>();
            this.CustomerDelayPayments1 = new HashSet<CustomerDelayPayment>();
            this.CustomerMonthlySalesAmounts = new HashSet<CustomerMonthlySalesAmount>();
            this.CustomerMonthlySalesAmounts1 = new HashSet<CustomerMonthlySalesAmount>();
            this.CustomerOutsourceAmounts = new HashSet<CustomerOutsourceAmount>();
            this.CustomerOutsourceAmounts1 = new HashSet<CustomerOutsourceAmount>();
            this.CustomerProductTypes = new HashSet<CustomerProductType>();
            this.CustomerProductTypes1 = new HashSet<CustomerProductType>();
            this.CustomerSalesAmounts = new HashSet<CustomerSalesAmount>();
            this.CustomerSalesAmounts1 = new HashSet<CustomerSalesAmount>();
            this.CustomerSalesProductTypes = new HashSet<CustomerSalesProductType>();
            this.CustomerSalesProductTypes1 = new HashSet<CustomerSalesProductType>();
            this.CustomerSites = new HashSet<CustomerSite>();
            this.CustomerSites1 = new HashSet<CustomerSite>();
            this.DistributionChannels = new HashSet<DistributionChannel>();
            this.DistributionChannels1 = new HashSet<DistributionChannel>();
            this.InfoFabEmpLeaves = new HashSet<InfoFabEmpLeave>();
            this.InfoFabEmpLeaves1 = new HashSet<InfoFabEmpLeave>();
            this.InfoFabEmpLeaveDays = new HashSet<InfoFabEmpLeaveDay>();
            this.InfoFabEmpLeaveDays1 = new HashSet<InfoFabEmpLeaveDay>();
            this.InfoFabEmpOvertimes = new HashSet<InfoFabEmpOvertime>();
            this.InfoFabEmpOvertimes1 = new HashSet<InfoFabEmpOvertime>();
            this.InfoFabEmpProcEffs = new HashSet<InfoFabEmpProcEff>();
            this.InfoFabEmpProcEffs1 = new HashSet<InfoFabEmpProcEff>();
            this.InfoFabEmpSkills = new HashSet<InfoFabEmpSkill>();
            this.InfoFabEmpSkills1 = new HashSet<InfoFabEmpSkill>();
            this.InfoFabEmpSkillClasses = new HashSet<InfoFabEmpSkillClass>();
            this.InfoFabEmpSkillClasses1 = new HashSet<InfoFabEmpSkillClass>();
            this.InfoFabEmpTaskAssigns = new HashSet<InfoFabEmpTaskAssign>();
            this.InfoFabEmpTaskAssigns1 = new HashSet<InfoFabEmpTaskAssign>();
            this.InfoFabEmpTaskDailyRecords = new HashSet<InfoFabEmpTaskDailyRecord>();
            this.InfoFabEmpTaskDailyRecords1 = new HashSet<InfoFabEmpTaskDailyRecord>();
            this.InfoFabLeaveCodes = new HashSet<InfoFabLeaveCode>();
            this.InfoFabLeaveCodes1 = new HashSet<InfoFabLeaveCode>();
            this.InfoFabOffDays = new HashSet<InfoFabOffDay>();
            this.InfoFabOffDays1 = new HashSet<InfoFabOffDay>();
            this.InfoFabOvertimeCodes = new HashSet<InfoFabOvertimeCode>();
            this.InfoFabOvertimeCodes1 = new HashSet<InfoFabOvertimeCode>();
            this.InfoFabPayControls = new HashSet<InfoFabPayControl>();
            this.InfoFabPayControls1 = new HashSet<InfoFabPayControl>();
            this.InfoFabPayPeriods = new HashSet<InfoFabPayPeriod>();
            this.InfoFabPayPeriods1 = new HashSet<InfoFabPayPeriod>();
            this.InfoFabProcedures = new HashSet<InfoFabProcedure>();
            this.InfoFabProcedures1 = new HashSet<InfoFabProcedure>();
            this.InfoFabProCertSkills = new HashSet<InfoFabProCertSkill>();
            this.InfoFabProCertSkills1 = new HashSet<InfoFabProCertSkill>();
            this.InfoFabSkills = new HashSet<InfoFabSkill>();
            this.InfoFabSkills1 = new HashSet<InfoFabSkill>();
            this.InfoFabSkillTypes = new HashSet<InfoFabSkillType>();
            this.InfoFabSkillTypes1 = new HashSet<InfoFabSkillType>();
            this.InfoFabTasks = new HashSet<InfoFabTask>();
            this.InfoFabTasks1 = new HashSet<InfoFabTask>();
            this.InfoFabTaskDetails = new HashSet<InfoFabTaskDetail>();
            this.InfoFabTaskDetails1 = new HashSet<InfoFabTaskDetail>();
            this.InfoFabTaskEnvs = new HashSet<InfoFabTaskEnv>();
            this.InfoFabTaskEnvs1 = new HashSet<InfoFabTaskEnv>();
            this.InfoFabTaskKinds = new HashSet<InfoFabTaskKind>();
            this.InfoFabTaskKinds1 = new HashSet<InfoFabTaskKind>();
            this.InfoFabTaskProcedures = new HashSet<InfoFabTaskProcedure>();
            this.InfoFabTaskProcedures1 = new HashSet<InfoFabTaskProcedure>();
            this.InfoFabTaskProjects = new HashSet<InfoFabTaskProject>();
            this.InfoFabTaskProjects1 = new HashSet<InfoFabTaskProject>();
            this.InfoFabTaskProperties = new HashSet<InfoFabTaskProperty>();
            this.InfoFabTaskProperties1 = new HashSet<InfoFabTaskProperty>();
            this.InfoFabTaskPropTemplates = new HashSet<InfoFabTaskPropTemplate>();
            this.InfoFabTaskPropTemplates1 = new HashSet<InfoFabTaskPropTemplate>();
            this.InfoFabUser1 = new HashSet<InfoFabUser>();
            this.InfoFabUser11 = new HashSet<InfoFabUser>();
            this.InfoFabUserAuths = new HashSet<InfoFabUserAuth>();
            this.InfoFabUserAuths1 = new HashSet<InfoFabUserAuth>();
            this.InfoFabUserAuths2 = new HashSet<InfoFabUserAuth>();
            this.InfoFabWFForms = new HashSet<InfoFabWFForm>();
            this.InfoFabWFForms1 = new HashSet<InfoFabWFForm>();
            this.InfoFabWFProjectTests = new HashSet<InfoFabWFProjectTest>();
            this.InfoFabWFProjectTests1 = new HashSet<InfoFabWFProjectTest>();
            this.InfoFabWFProjectTestHistories = new HashSet<InfoFabWFProjectTestHistory>();
            this.InfoFabWFProjectTestHistories1 = new HashSet<InfoFabWFProjectTestHistory>();
            this.InfoFabWFSchemes = new HashSet<InfoFabWFScheme>();
            this.InfoFabWFSchemes1 = new HashSet<InfoFabWFScheme>();
            this.InfoFabWFSchemeHistories = new HashSet<InfoFabWFSchemeHistory>();
            this.InfoFabWFSchemeHistories1 = new HashSet<InfoFabWFSchemeHistory>();
            this.InfoFabWorkCodes = new HashSet<InfoFabWorkCode>();
            this.InfoFabWorkCodes1 = new HashSet<InfoFabWorkCode>();
            this.InfoFabWorkGroups = new HashSet<InfoFabWorkGroup>();
            this.InfoFabWorkGroups1 = new HashSet<InfoFabWorkGroup>();
            this.InfoFabWorkPatterns = new HashSet<InfoFabWorkPattern>();
            this.InfoFabWorkPatterns1 = new HashSet<InfoFabWorkPattern>();
            this.JJMFEmpProcedures = new HashSet<JJMFEmpProcedure>();
            this.JJMFEmpProcedures1 = new HashSet<JJMFEmpProcedure>();
            this.JJMFEmpTaskDailyDisplays = new HashSet<JJMFEmpTaskDailyDisplay>();
            this.JJMFEmpTaskDailyDisplays1 = new HashSet<JJMFEmpTaskDailyDisplay>();
            this.JJMFEmpTaskDailyRecords = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFEmpTaskDailyRecords1 = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFProcedures = new HashSet<JJMFProcedure>();
            this.JJMFProcedures1 = new HashSet<JJMFProcedure>();
            this.JJMFTasks = new HashSet<JJMFTask>();
            this.JJMFTasks1 = new HashSet<JJMFTask>();
            this.JJMFTaskCals = new HashSet<JJMFTaskCal>();
            this.JJMFTaskCals1 = new HashSet<JJMFTaskCal>();
            this.JJMFTaskCalItems = new HashSet<JJMFTaskCalItem>();
            this.JJMFTaskCalItems1 = new HashSet<JJMFTaskCalItem>();
            this.PartClasses = new HashSet<PartClass>();
            this.PartClasses1 = new HashSet<PartClass>();
            this.PartLovCodes = new HashSet<PartLovCode>();
            this.PartLovCodes1 = new HashSet<PartLovCode>();
            this.PartLovKinds = new HashSet<PartLovKind>();
            this.PartLovKinds1 = new HashSet<PartLovKind>();
            this.PartLovTypes = new HashSet<PartLovType>();
            this.PartLovTypes1 = new HashSet<PartLovType>();
            this.PartSerialNoRules = new HashSet<PartSerialNoRule>();
            this.PartSerialNoRules1 = new HashSet<PartSerialNoRule>();
            this.PartTypes = new HashSet<PartType>();
            this.PartTypes1 = new HashSet<PartType>();
            this.PartTypeClasses = new HashSet<PartTypeClass>();
            this.PartTypeClasses1 = new HashSet<PartTypeClass>();
            this.PartTypeMaterialModels = new HashSet<PartTypeMaterialModel>();
            this.PartTypeMaterialModels1 = new HashSet<PartTypeMaterialModel>();
            this.PartTypeSerialNoes = new HashSet<PartTypeSerialNo>();
            this.PartTypeSerialNoes1 = new HashSet<PartTypeSerialNo>();
            this.SalesAreas = new HashSet<SalesArea>();
            this.SalesAreas1 = new HashSet<SalesArea>();
            this.SalesOrganizations = new HashSet<SalesOrganization>();
            this.SalesOrganizations1 = new HashSet<SalesOrganization>();
        }
    
        public string ID { get; set; }
        public Nullable<System.Guid> LangID { get; set; }
        public string UserName { get; set; }
        public string DisplayName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public Nullable<System.Guid> UserType { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsAdmin { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ExpiredDT { get; set; }
        public Nullable<System.DateTime> LastLogonDT { get; set; }
        public Nullable<System.Guid> EID { get; set; }
        public Nullable<int> MaxTimeOut { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAnnualLeave> InfoFabAnnualLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAnnualLeave> InfoFabAnnualLeaves1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAnnualLeaveCondition> InfoFabAnnualLeaveConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAnnualLeaveCondition> InfoFabAnnualLeaveConditions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAttnEnv> InfoFabAttnEnvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAttnEnv> InfoFabAttnEnvs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabArea> InfoFabAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabArea> InfoFabAreas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCatContent> InfoFabCatContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCatContent> InfoFabCatContents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCategory> InfoFabCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCategory> InfoFabCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabClass> InfoFabClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabClass> InfoFabClasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCode> InfoFabCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCode> InfoFabCodes1 { get; set; }
        public virtual InfoFabCode InfoFabCode { get; set; }
        public virtual InfoFabCode InfoFabCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabColumn> InfoFabColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabColumn> InfoFabColumns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabColumnsSetting> InfoFabColumnsSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabColumnsSetting> InfoFabColumnsSettings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabDistrict> InfoFabDistricts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabDistrict> InfoFabDistricts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpDeputy> InfoFabEmpDeputies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpDeputy> InfoFabEmpDeputies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOrg> InfoFabEmpOrgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOrg> InfoFabEmpOrgs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpProCert> InfoFabEmpProCerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpProCert> InfoFabEmpProCerts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabENV> InfoFabENVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabENV> InfoFabENVs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabENVItem> InfoFabENVItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabENVItem> InfoFabENVItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabForgotPWD> InfoFabForgotPWDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabForgotPWD> InfoFabForgotPWDs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabLangMapping> InfoFabLangMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabLangMapping> InfoFabLangMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabMessage> InfoFabMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabMessage> InfoFabMessages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabMessageContent> InfoFabMessageContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabMessageContent> InfoFabMessageContents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabNotify> InfoFabNotifies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabNotify> InfoFabNotifies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabNotify> InfoFabNotifies2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOrganization> InfoFabOrganizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOrganization> InfoFabOrganizations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOrgEnv> InfoFabOrgEnvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOrgEnv> InfoFabOrgEnvs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPersonal> InfoFabPersonals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPersonal> InfoFabPersonals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProCert> InfoFabProCerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProCert> InfoFabProCerts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProject> InfoFabProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProject> InfoFabProjects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProject> InfoFabProjects2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProjectAttendee> InfoFabProjectAttendees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProjectAttendee> InfoFabProjectAttendees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProjectAttendee> InfoFabProjectAttendees2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProjectClass> InfoFabProjectClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProjectClass> InfoFabProjectClasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProjectNode> InfoFabProjectNodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProjectNode> InfoFabProjectNodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRole> InfoFabRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRole> InfoFabRoles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRoleAuth> InfoFabRoleAuths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRoleAuth> InfoFabRoleAuths1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRoleUser> InfoFabRoleUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRoleUser> InfoFabRoleUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRoleUser> InfoFabRoleUsers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTable> InfoFabTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTable> InfoFabTables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabType> InfoFabTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabType> InfoFabTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBusinessPartner> CustomerBusinessPartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBusinessPartner> CustomerBusinessPartners1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBusinessType> CustomerBusinessTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBusinessType> CustomerBusinessTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactOwner> CustomerContactOwners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactOwner> CustomerContactOwners1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactPerson> CustomerContactPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactPerson> CustomerContactPersons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCreditLimit> CustomerCreditLimits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCreditLimit> CustomerCreditLimits1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDelayPayment> CustomerDelayPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDelayPayment> CustomerDelayPayments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMonthlySalesAmount> CustomerMonthlySalesAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMonthlySalesAmount> CustomerMonthlySalesAmounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOutsourceAmount> CustomerOutsourceAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOutsourceAmount> CustomerOutsourceAmounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProductType> CustomerProductTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProductType> CustomerProductTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSalesAmount> CustomerSalesAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSalesAmount> CustomerSalesAmounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSalesProductType> CustomerSalesProductTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSalesProductType> CustomerSalesProductTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSite> CustomerSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSite> CustomerSites1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributionChannel> DistributionChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributionChannel> DistributionChannels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeave> InfoFabEmpLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeave> InfoFabEmpLeaves1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeaveDay> InfoFabEmpLeaveDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeaveDay> InfoFabEmpLeaveDays1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOvertime> InfoFabEmpOvertimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOvertime> InfoFabEmpOvertimes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpProcEff> InfoFabEmpProcEffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpProcEff> InfoFabEmpProcEffs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpSkill> InfoFabEmpSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpSkill> InfoFabEmpSkills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpSkillClass> InfoFabEmpSkillClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpSkillClass> InfoFabEmpSkillClasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpTaskAssign> InfoFabEmpTaskAssigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpTaskAssign> InfoFabEmpTaskAssigns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpTaskDailyRecord> InfoFabEmpTaskDailyRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpTaskDailyRecord> InfoFabEmpTaskDailyRecords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabLeaveCode> InfoFabLeaveCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabLeaveCode> InfoFabLeaveCodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOffDay> InfoFabOffDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOffDay> InfoFabOffDays1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOvertimeCode> InfoFabOvertimeCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOvertimeCode> InfoFabOvertimeCodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPayControl> InfoFabPayControls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPayControl> InfoFabPayControls1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPayPeriod> InfoFabPayPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPayPeriod> InfoFabPayPeriods1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProcedure> InfoFabProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProcedure> InfoFabProcedures1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProCertSkill> InfoFabProCertSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProCertSkill> InfoFabProCertSkills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabSkill> InfoFabSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabSkill> InfoFabSkills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabSkillType> InfoFabSkillTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabSkillType> InfoFabSkillTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTask> InfoFabTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTask> InfoFabTasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskDetail> InfoFabTaskDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskDetail> InfoFabTaskDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskEnv> InfoFabTaskEnvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskEnv> InfoFabTaskEnvs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskKind> InfoFabTaskKinds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskKind> InfoFabTaskKinds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskProcedure> InfoFabTaskProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskProcedure> InfoFabTaskProcedures1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskProject> InfoFabTaskProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskProject> InfoFabTaskProjects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskProperty> InfoFabTaskProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskProperty> InfoFabTaskProperties1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskPropTemplate> InfoFabTaskPropTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskPropTemplate> InfoFabTaskPropTemplates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUser> InfoFabUser1 { get; set; }
        public virtual InfoFabUser InfoFabUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUser> InfoFabUser11 { get; set; }
        public virtual InfoFabUser InfoFabUser3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUserAuth> InfoFabUserAuths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUserAuth> InfoFabUserAuths1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUserAuth> InfoFabUserAuths2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWFForm> InfoFabWFForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWFForm> InfoFabWFForms1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWFProjectTest> InfoFabWFProjectTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWFProjectTest> InfoFabWFProjectTests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWFProjectTestHistory> InfoFabWFProjectTestHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWFProjectTestHistory> InfoFabWFProjectTestHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWFScheme> InfoFabWFSchemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWFScheme> InfoFabWFSchemes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWFSchemeHistory> InfoFabWFSchemeHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWFSchemeHistory> InfoFabWFSchemeHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkCode> InfoFabWorkCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkCode> InfoFabWorkCodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkGroup> InfoFabWorkGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkGroup> InfoFabWorkGroups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkPattern> InfoFabWorkPatterns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkPattern> InfoFabWorkPatterns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpProcedure> JJMFEmpProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpProcedure> JJMFEmpProcedures1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyDisplay> JJMFEmpTaskDailyDisplays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyDisplay> JJMFEmpTaskDailyDisplays1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFProcedure> JJMFProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFProcedure> JJMFProcedures1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTask> JJMFTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTask> JJMFTasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTaskCal> JJMFTaskCals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTaskCal> JJMFTaskCals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTaskCalItem> JJMFTaskCalItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTaskCalItem> JJMFTaskCalItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartClass> PartClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartClass> PartClasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartLovCode> PartLovCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartLovCode> PartLovCodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartLovKind> PartLovKinds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartLovKind> PartLovKinds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartLovType> PartLovTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartLovType> PartLovTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartSerialNoRule> PartSerialNoRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartSerialNoRule> PartSerialNoRules1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartType> PartTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartType> PartTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartTypeClass> PartTypeClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartTypeClass> PartTypeClasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartTypeMaterialModel> PartTypeMaterialModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartTypeMaterialModel> PartTypeMaterialModels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartTypeSerialNo> PartTypeSerialNoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartTypeSerialNo> PartTypeSerialNoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesArea> SalesAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesArea> SalesAreas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrganization> SalesOrganizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrganization> SalesOrganizations1 { get; set; }
    }
}
