//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabWinScheduler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabWinScheduler()
        {
            this.InfoFabWinSchExeHistories = new HashSet<InfoFabWinSchExeHistory>();
        }
    
        public System.Guid ID { get; set; }
        public string JobName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string PeriodMode { get; set; }
        public int Interval { get; set; }
        public string Customized { get; set; }
        public string FilePath { get; set; }
        public string ClassName { get; set; }
        public string exJobName { get; set; }
        public string exPeriodMode { get; set; }
        public Nullable<int> exInterval { get; set; }
        public string exCustomized { get; set; }
        public string exFilePath { get; set; }
        public string exClassName { get; set; }
        public bool Enabled { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWinSchExeHistory> InfoFabWinSchExeHistories { get; set; }
    }
}
