//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabAttnEnv
    {
        public System.Guid ID { get; set; }
        public Nullable<bool> IsDeputyApply { get; set; }
        public Nullable<System.Guid> DefaultLeaveDeputyType { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
        public Nullable<System.Guid> AnnualLeaveCountType { get; set; }
        public Nullable<int> OTCompensatoryValidMonths { get; set; }
        public Nullable<int> ExtendMonth { get; set; }
        public Nullable<int> MaxExtendTimes { get; set; }
        public Nullable<System.Guid> AnnualLeaveCode { get; set; }
        public Nullable<System.Guid> CompensatoryLeaveCode { get; set; }
        public Nullable<int> AnnualLeaveRecallDays { get; set; }
    
        public virtual InfoFabCode InfoFabCode { get; set; }
        public virtual InfoFabCode InfoFabCode1 { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
    }
}
