//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabLeaveCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabLeaveCode()
        {
            this.InfoFabEmpLeaves = new HashSet<InfoFabEmpLeave>();
            this.InfoFabEmpLeaveDaysControls = new HashSet<InfoFabEmpLeaveDaysControl>();
            this.InfoFabLeaveCode1 = new HashSet<InfoFabLeaveCode>();
        }
    
        public System.Guid ID { get; set; }
        public string LeaveCode { get; set; }
        public string LeaveName { get; set; }
        public Nullable<System.Guid> DependOn { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> ReduceRate { get; set; }
        public Nullable<decimal> MinTime { get; set; }
        public string MinTimeUnit { get; set; }
        public Nullable<decimal> IncTime { get; set; }
        public string IncTimeUnit { get; set; }
        public Nullable<decimal> AnnualLimitDays { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeave> InfoFabEmpLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeaveDaysControl> InfoFabEmpLeaveDaysControls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabLeaveCode> InfoFabLeaveCode1 { get; set; }
        public virtual InfoFabLeaveCode InfoFabLeaveCode2 { get; set; }
    }
}
