//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabTaskProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabTaskProject()
        {
            this.InfoFabTasks = new HashSet<InfoFabTask>();
        }
    
        public System.Guid ID { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public System.Guid ProjectType { get; set; }
        public System.Guid PMEmpOrgID { get; set; }
        public System.DateTime CalSDate { get; set; }
        public System.DateTime CalEDate { get; set; }
        public Nullable<System.DateTime> ActualSDate { get; set; }
        public Nullable<System.DateTime> ActualEDate { get; set; }
        public decimal TotalQty { get; set; }
        public string TotalUnit { get; set; }
        public System.Guid ProjectStatus { get; set; }
        public Nullable<System.Guid> FPID { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        public virtual InfoFabCode InfoFabCode { get; set; }
        public virtual InfoFabCode InfoFabCode1 { get; set; }
        public virtual InfoFabEmpOrg InfoFabEmpOrg { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTask> InfoFabTasks { get; set; }
    }
}
