//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabPayControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabPayControl()
        {
            this.InfoFabEmpLeaves = new HashSet<InfoFabEmpLeave>();
            this.InfoFabEmpLeaveDays = new HashSet<InfoFabEmpLeaveDay>();
            this.InfoFabEmpOvertimes = new HashSet<InfoFabEmpOvertime>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PPID { get; set; }
        public string PCName { get; set; }
        public Nullable<System.DateTime> Sdate { get; set; }
        public Nullable<System.DateTime> Edate { get; set; }
        public Nullable<System.DateTime> TimeSdate { get; set; }
        public Nullable<System.DateTime> TimeEdate { get; set; }
        public Nullable<System.DateTime> OTSdate { get; set; }
        public Nullable<System.DateTime> OTEdate { get; set; }
        public Nullable<System.DateTime> LeaveSdate { get; set; }
        public Nullable<System.DateTime> LeaveEdate { get; set; }
        public Nullable<System.DateTime> FinanceConfirmDate { get; set; }
        public Nullable<System.DateTime> HRConfirmationDate { get; set; }
        public Nullable<System.DateTime> GeneralConfirmDate { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeave> InfoFabEmpLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeaveDay> InfoFabEmpLeaveDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOvertime> InfoFabEmpOvertimes { get; set; }
        public virtual InfoFabPayPeriod InfoFabPayPeriod { get; set; }
    }
}
