//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabCode()
        {
            this.InfoFabAttnEnvs = new HashSet<InfoFabAttnEnv>();
            this.InfoFabAttnEnvs1 = new HashSet<InfoFabAttnEnv>();
            this.InfoFabContents = new HashSet<InfoFabContent>();
            this.InfoFabContents1 = new HashSet<InfoFabContent>();
            this.InfoFabContents2 = new HashSet<InfoFabContent>();
            this.InfoFabEmpDeputies = new HashSet<InfoFabEmpDeputy>();
            this.InfoFabEmpLeaves = new HashSet<InfoFabEmpLeave>();
            this.InfoFabEmployees = new HashSet<InfoFabEmployee>();
            this.InfoFabEmployees1 = new HashSet<InfoFabEmployee>();
            this.InfoFabEmployees2 = new HashSet<InfoFabEmployee>();
            this.InfoFabEmployees3 = new HashSet<InfoFabEmployee>();
            this.InfoFabEmpOrgs = new HashSet<InfoFabEmpOrg>();
            this.InfoFabEmpOvertimes = new HashSet<InfoFabEmpOvertime>();
            this.InfoFabLangMappings = new HashSet<InfoFabLangMapping>();
            this.InfoFabMessages = new HashSet<InfoFabMessage>();
            this.InfoFabOffDays = new HashSet<InfoFabOffDay>();
            this.InfoFabOrganizations = new HashSet<InfoFabOrganization>();
            this.InfoFabPayPeriods = new HashSet<InfoFabPayPeriod>();
            this.InfoFabPersonals = new HashSet<InfoFabPersonal>();
            this.InfoFabProCerts = new HashSet<InfoFabProCert>();
            this.InfoFabRoles = new HashSet<InfoFabRole>();
            this.InfoFabUsers = new HashSet<InfoFabUser>();
            this.InfoFabUsers1 = new HashSet<InfoFabUser>();
            this.JJMFEmpTaskDailyRecords = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFEmpTaskDailyRecords1 = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFEmpTaskDailyRecords2 = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFEmpTaskDailyRecords3 = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFTasks = new HashSet<JJMFTask>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TypeID { get; set; }
        public string Code { get; set; }
        public string CodeName { get; set; }
        public string AliasName { get; set; }
        public string Remark { get; set; }
        public int Seq { get; set; }
        public bool IsDefault { get; set; }
        public string OriginalCode { get; set; }
        public bool IsSysControl { get; set; }
        public bool IsEnabled { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAttnEnv> InfoFabAttnEnvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAttnEnv> InfoFabAttnEnvs1 { get; set; }
        public virtual InfoFabType InfoFabType { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpDeputy> InfoFabEmpDeputies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeave> InfoFabEmpLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOrg> InfoFabEmpOrgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOvertime> InfoFabEmpOvertimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabLangMapping> InfoFabLangMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabMessage> InfoFabMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOffDay> InfoFabOffDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOrganization> InfoFabOrganizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPayPeriod> InfoFabPayPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPersonal> InfoFabPersonals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProCert> InfoFabProCerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRole> InfoFabRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUser> InfoFabUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUser> InfoFabUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTask> JJMFTasks { get; set; }
    }
}
