//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabCode()
        {
            this.InfoFabAttnEnvs = new HashSet<InfoFabAttnEnv>();
            this.Customers = new HashSet<Customer>();
            this.Customers1 = new HashSet<Customer>();
            this.CustomerBusinessPartners = new HashSet<CustomerBusinessPartner>();
            this.CustomerBusinessTypes = new HashSet<CustomerBusinessType>();
            this.CustomerBusinessTypes1 = new HashSet<CustomerBusinessType>();
            this.CustomerContactOwners = new HashSet<CustomerContactOwner>();
            this.CustomerContactPersons = new HashSet<CustomerContactPerson>();
            this.CustomerContactPersons1 = new HashSet<CustomerContactPerson>();
            this.CustomerCreditLimits = new HashSet<CustomerCreditLimit>();
            this.CustomerCreditLimits1 = new HashSet<CustomerCreditLimit>();
            this.CustomerCreditLimits2 = new HashSet<CustomerCreditLimit>();
            this.CustomerCreditLimits3 = new HashSet<CustomerCreditLimit>();
            this.CustomerCreditLimits4 = new HashSet<CustomerCreditLimit>();
            this.CustomerMonthlySalesAmounts = new HashSet<CustomerMonthlySalesAmount>();
            this.CustomerOutsourceAmounts = new HashSet<CustomerOutsourceAmount>();
            this.CustomerProductTypes = new HashSet<CustomerProductType>();
            this.CustomerSalesAmounts = new HashSet<CustomerSalesAmount>();
            this.CustomerSalesProductTypes = new HashSet<CustomerSalesProductType>();
            this.CustomerSites = new HashSet<CustomerSite>();
            this.InfoFabContents = new HashSet<InfoFabContent>();
            this.InfoFabContents1 = new HashSet<InfoFabContent>();
            this.InfoFabContents2 = new HashSet<InfoFabContent>();
            this.InfoFabEmpDeputies = new HashSet<InfoFabEmpDeputy>();
            this.InfoFabEmpLeaves = new HashSet<InfoFabEmpLeave>();
            this.InfoFabEmployees = new HashSet<InfoFabEmployee>();
            this.InfoFabEmployees1 = new HashSet<InfoFabEmployee>();
            this.InfoFabEmployees2 = new HashSet<InfoFabEmployee>();
            this.InfoFabEmployees3 = new HashSet<InfoFabEmployee>();
            this.InfoFabEmpOrgs = new HashSet<InfoFabEmpOrg>();
            this.InfoFabEmpOvertimes = new HashSet<InfoFabEmpOvertime>();
            this.InfoFabEmpSkillClasses = new HashSet<InfoFabEmpSkillClass>();
            this.InfoFabEmpSkillClasses1 = new HashSet<InfoFabEmpSkillClass>();
            this.InfoFabEmpTaskDailyRecords = new HashSet<InfoFabEmpTaskDailyRecord>();
            this.InfoFabEmpTaskDailyRecords1 = new HashSet<InfoFabEmpTaskDailyRecord>();
            this.InfoFabEmpTaskDailyRecords2 = new HashSet<InfoFabEmpTaskDailyRecord>();
            this.InfoFabLangMappings = new HashSet<InfoFabLangMapping>();
            this.InfoFabMessages = new HashSet<InfoFabMessage>();
            this.InfoFabOffDays = new HashSet<InfoFabOffDay>();
            this.InfoFabOrganizations = new HashSet<InfoFabOrganization>();
            this.InfoFabPayPeriods = new HashSet<InfoFabPayPeriod>();
            this.InfoFabPersonals = new HashSet<InfoFabPersonal>();
            this.InfoFabProCerts = new HashSet<InfoFabProCert>();
            this.InfoFabProjects = new HashSet<InfoFabProject>();
            this.InfoFabRoles = new HashSet<InfoFabRole>();
            this.InfoFabTasks = new HashSet<InfoFabTask>();
            this.InfoFabTaskProcedures = new HashSet<InfoFabTaskProcedure>();
            this.InfoFabTaskProjects = new HashSet<InfoFabTaskProject>();
            this.InfoFabTaskProjects1 = new HashSet<InfoFabTaskProject>();
            this.InfoFabTaskPropTemplates = new HashSet<InfoFabTaskPropTemplate>();
            this.InfoFabUsers = new HashSet<InfoFabUser>();
            this.InfoFabUsers1 = new HashSet<InfoFabUser>();
            this.InfoFabWFProjectTests = new HashSet<InfoFabWFProjectTest>();
            this.JJMFEmpTaskDailyRecords = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFEmpTaskDailyRecords1 = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFEmpTaskDailyRecords2 = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFEmpTaskDailyRecords3 = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFTasks = new HashSet<JJMFTask>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TypeID { get; set; }
        public string Code { get; set; }
        public string CodeName { get; set; }
        public string AliasName { get; set; }
        public string Remark { get; set; }
        public int Seq { get; set; }
        public bool IsDefault { get; set; }
        public string OriginalCode { get; set; }
        public bool IsSysControl { get; set; }
        public bool IsEnabled { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAttnEnv> InfoFabAttnEnvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBusinessPartner> CustomerBusinessPartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBusinessType> CustomerBusinessTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBusinessType> CustomerBusinessTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactOwner> CustomerContactOwners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactPerson> CustomerContactPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactPerson> CustomerContactPersons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCreditLimit> CustomerCreditLimits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCreditLimit> CustomerCreditLimits1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCreditLimit> CustomerCreditLimits2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCreditLimit> CustomerCreditLimits3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCreditLimit> CustomerCreditLimits4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMonthlySalesAmount> CustomerMonthlySalesAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOutsourceAmount> CustomerOutsourceAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProductType> CustomerProductTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSalesAmount> CustomerSalesAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSalesProductType> CustomerSalesProductTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSite> CustomerSites { get; set; }
        public virtual InfoFabType InfoFabType { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpDeputy> InfoFabEmpDeputies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeave> InfoFabEmpLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOrg> InfoFabEmpOrgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOvertime> InfoFabEmpOvertimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpSkillClass> InfoFabEmpSkillClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpSkillClass> InfoFabEmpSkillClasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpTaskDailyRecord> InfoFabEmpTaskDailyRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpTaskDailyRecord> InfoFabEmpTaskDailyRecords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpTaskDailyRecord> InfoFabEmpTaskDailyRecords2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabLangMapping> InfoFabLangMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabMessage> InfoFabMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOffDay> InfoFabOffDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOrganization> InfoFabOrganizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPayPeriod> InfoFabPayPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPersonal> InfoFabPersonals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProCert> InfoFabProCerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProject> InfoFabProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRole> InfoFabRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTask> InfoFabTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskProcedure> InfoFabTaskProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskProject> InfoFabTaskProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskProject> InfoFabTaskProjects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskPropTemplate> InfoFabTaskPropTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUser> InfoFabUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUser> InfoFabUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWFProjectTest> InfoFabWFProjectTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTask> JJMFTasks { get; set; }
    }
}
