//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabENVItem
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ENVID { get; set; }
        public string ParaName { get; set; }
        public string ParaDataType { get; set; }
        public string ParaValue { get; set; }
        public string Remark { get; set; }
        public string InitUID { get; set; }
        public Nullable<System.DateTime> InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public Nullable<System.DateTime> ModifiedDT { get; set; }
    
        public virtual InfoFabENV InfoFabENV { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
    }
}
