//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabPayPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabPayPeriod()
        {
            this.InfoFabPayControls = new HashSet<InfoFabPayControl>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PayType { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public int PeriodSeq { get; set; }
        public Nullable<int> Smonth { get; set; }
        public Nullable<int> Sday { get; set; }
        public Nullable<int> Emonth { get; set; }
        public Nullable<int> Eday { get; set; }
        public Nullable<int> TimeSmonth { get; set; }
        public Nullable<int> TimeSday { get; set; }
        public Nullable<int> TimeEmonth { get; set; }
        public Nullable<int> TimeEday { get; set; }
        public Nullable<int> OTSmonth { get; set; }
        public Nullable<int> OTSday { get; set; }
        public Nullable<int> OTEmonth { get; set; }
        public Nullable<int> OTEday { get; set; }
        public Nullable<int> LeaveSmonth { get; set; }
        public Nullable<int> LeaveSday { get; set; }
        public Nullable<int> LeaveEmonth { get; set; }
        public Nullable<int> LeaveEday { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        public virtual InfoFabCode InfoFabCode { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPayControl> InfoFabPayControls { get; set; }
    }
}
