//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabCategory()
        {
            this.InfoFabCatContents = new HashSet<InfoFabCatContent>();
            this.InfoFabCategory1 = new HashSet<InfoFabCategory>();
        }
    
        public System.Guid ID { get; set; }
        public string CategoryName { get; set; }
        public string AliasName { get; set; }
        public string LinkPath { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public string Area { get; set; }
        public string Description { get; set; }
        public string IconPath { get; set; }
        public Nullable<System.Guid> PID { get; set; }
        public string PIDs { get; set; }
        public Nullable<bool> IsCollectionParent { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Seq { get; set; }
        public bool IsEnabled { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCatContent> InfoFabCatContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCategory> InfoFabCategory1 { get; set; }
        public virtual InfoFabCategory InfoFabCategory2 { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
    }
}
