//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabUser()
        {
            this.InfoFabAnnualLeaveConditions = new HashSet<InfoFabAnnualLeaveCondition>();
            this.InfoFabAnnualLeaveConditions1 = new HashSet<InfoFabAnnualLeaveCondition>();
            this.InfoFabAttnEnvs = new HashSet<InfoFabAttnEnv>();
            this.InfoFabAttnEnvs1 = new HashSet<InfoFabAttnEnv>();
            this.InfoFabCatContents = new HashSet<InfoFabCatContent>();
            this.InfoFabCatContents1 = new HashSet<InfoFabCatContent>();
            this.InfoFabCategories = new HashSet<InfoFabCategory>();
            this.InfoFabCategories1 = new HashSet<InfoFabCategory>();
            this.InfoFabCodes = new HashSet<InfoFabCode>();
            this.InfoFabCodes1 = new HashSet<InfoFabCode>();
            this.InfoFabColumns = new HashSet<InfoFabColumn>();
            this.InfoFabColumns1 = new HashSet<InfoFabColumn>();
            this.InfoFabColumnsSettings = new HashSet<InfoFabColumnsSetting>();
            this.InfoFabColumnsSettings1 = new HashSet<InfoFabColumnsSetting>();
            this.InfoFabContents = new HashSet<InfoFabContent>();
            this.InfoFabContents1 = new HashSet<InfoFabContent>();
            this.InfoFabContents2 = new HashSet<InfoFabContent>();
            this.InfoFabEmpDeputies = new HashSet<InfoFabEmpDeputy>();
            this.InfoFabEmpDeputies1 = new HashSet<InfoFabEmpDeputy>();
            this.InfoFabEmployees = new HashSet<InfoFabEmployee>();
            this.InfoFabEmployees1 = new HashSet<InfoFabEmployee>();
            this.InfoFabEmpOrgs = new HashSet<InfoFabEmpOrg>();
            this.InfoFabEmpOrgs1 = new HashSet<InfoFabEmpOrg>();
            this.InfoFabEmpProCerts = new HashSet<InfoFabEmpProCert>();
            this.InfoFabEmpProCerts1 = new HashSet<InfoFabEmpProCert>();
            this.InfoFabENVs = new HashSet<InfoFabENV>();
            this.InfoFabENVs1 = new HashSet<InfoFabENV>();
            this.InfoFabENVItems = new HashSet<InfoFabENVItem>();
            this.InfoFabENVItems1 = new HashSet<InfoFabENVItem>();
            this.InfoFabForgotPWDs = new HashSet<InfoFabForgotPWD>();
            this.InfoFabForgotPWDs1 = new HashSet<InfoFabForgotPWD>();
            this.InfoFabJobSchedulers = new HashSet<InfoFabJobScheduler>();
            this.InfoFabJobSchedulers1 = new HashSet<InfoFabJobScheduler>();
            this.InfoFabLangMappings = new HashSet<InfoFabLangMapping>();
            this.InfoFabLangMappings1 = new HashSet<InfoFabLangMapping>();
            this.InfoFabMessages = new HashSet<InfoFabMessage>();
            this.InfoFabMessages1 = new HashSet<InfoFabMessage>();
            this.InfoFabMessageContents = new HashSet<InfoFabMessageContent>();
            this.InfoFabMessageContents1 = new HashSet<InfoFabMessageContent>();
            this.InfoFabNotifies = new HashSet<InfoFabNotify>();
            this.InfoFabNotifies1 = new HashSet<InfoFabNotify>();
            this.InfoFabNotifies2 = new HashSet<InfoFabNotify>();
            this.InfoFabOrganizations = new HashSet<InfoFabOrganization>();
            this.InfoFabOrganizations1 = new HashSet<InfoFabOrganization>();
            this.InfoFabOrgEnvs = new HashSet<InfoFabOrgEnv>();
            this.InfoFabOrgEnvs1 = new HashSet<InfoFabOrgEnv>();
            this.InfoFabPersonals = new HashSet<InfoFabPersonal>();
            this.InfoFabPersonals1 = new HashSet<InfoFabPersonal>();
            this.InfoFabProCerts = new HashSet<InfoFabProCert>();
            this.InfoFabProCerts1 = new HashSet<InfoFabProCert>();
            this.InfoFabRoles = new HashSet<InfoFabRole>();
            this.InfoFabRoles1 = new HashSet<InfoFabRole>();
            this.InfoFabRoleAuths = new HashSet<InfoFabRoleAuth>();
            this.InfoFabRoleAuths1 = new HashSet<InfoFabRoleAuth>();
            this.InfoFabRoleUsers = new HashSet<InfoFabRoleUser>();
            this.InfoFabRoleUsers1 = new HashSet<InfoFabRoleUser>();
            this.InfoFabRoleUsers2 = new HashSet<InfoFabRoleUser>();
            this.InfoFabTables = new HashSet<InfoFabTable>();
            this.InfoFabTables1 = new HashSet<InfoFabTable>();
            this.InfoFabTypes = new HashSet<InfoFabType>();
            this.InfoFabTypes1 = new HashSet<InfoFabType>();
            this.InfoFabEmpLeaves = new HashSet<InfoFabEmpLeave>();
            this.InfoFabEmpLeaves1 = new HashSet<InfoFabEmpLeave>();
            this.InfoFabEmpLeaveDays = new HashSet<InfoFabEmpLeaveDay>();
            this.InfoFabEmpLeaveDays1 = new HashSet<InfoFabEmpLeaveDay>();
            this.InfoFabEmpLeaveDaysControls = new HashSet<InfoFabEmpLeaveDaysControl>();
            this.InfoFabEmpLeaveDaysControls1 = new HashSet<InfoFabEmpLeaveDaysControl>();
            this.InfoFabEmpOvertimes = new HashSet<InfoFabEmpOvertime>();
            this.InfoFabEmpOvertimes1 = new HashSet<InfoFabEmpOvertime>();
            this.InfoFabEmpSkills = new HashSet<InfoFabEmpSkill>();
            this.InfoFabEmpSkills1 = new HashSet<InfoFabEmpSkill>();
            this.InfoFabLeaveCodes = new HashSet<InfoFabLeaveCode>();
            this.InfoFabLeaveCodes1 = new HashSet<InfoFabLeaveCode>();
            this.InfoFabOffDays = new HashSet<InfoFabOffDay>();
            this.InfoFabOffDays1 = new HashSet<InfoFabOffDay>();
            this.InfoFabOvertimeCodes = new HashSet<InfoFabOvertimeCode>();
            this.InfoFabOvertimeCodes1 = new HashSet<InfoFabOvertimeCode>();
            this.InfoFabPayControls = new HashSet<InfoFabPayControl>();
            this.InfoFabPayControls1 = new HashSet<InfoFabPayControl>();
            this.InfoFabPayPeriods = new HashSet<InfoFabPayPeriod>();
            this.InfoFabPayPeriods1 = new HashSet<InfoFabPayPeriod>();
            this.InfoFabProCertSkills = new HashSet<InfoFabProCertSkill>();
            this.InfoFabProCertSkills1 = new HashSet<InfoFabProCertSkill>();
            this.InfoFabSkills = new HashSet<InfoFabSkill>();
            this.InfoFabSkills1 = new HashSet<InfoFabSkill>();
            this.InfoFabSkillTypes = new HashSet<InfoFabSkillType>();
            this.InfoFabSkillTypes1 = new HashSet<InfoFabSkillType>();
            this.InfoFabTaskEnvs = new HashSet<InfoFabTaskEnv>();
            this.InfoFabTaskEnvs1 = new HashSet<InfoFabTaskEnv>();
            this.InfoFabUser1 = new HashSet<InfoFabUser>();
            this.InfoFabUser11 = new HashSet<InfoFabUser>();
            this.InfoFabUserAuths = new HashSet<InfoFabUserAuth>();
            this.InfoFabUserAuths1 = new HashSet<InfoFabUserAuth>();
            this.InfoFabUserAuths2 = new HashSet<InfoFabUserAuth>();
            this.InfoFabWinSchedulers = new HashSet<InfoFabWinScheduler>();
            this.InfoFabWinSchedulers1 = new HashSet<InfoFabWinScheduler>();
            this.InfoFabWorkCodes = new HashSet<InfoFabWorkCode>();
            this.InfoFabWorkCodes1 = new HashSet<InfoFabWorkCode>();
            this.InfoFabWorkGroups = new HashSet<InfoFabWorkGroup>();
            this.InfoFabWorkGroups1 = new HashSet<InfoFabWorkGroup>();
            this.InfoFabWorkPatterns = new HashSet<InfoFabWorkPattern>();
            this.InfoFabWorkPatterns1 = new HashSet<InfoFabWorkPattern>();
            this.JJMFEmpProcedures = new HashSet<JJMFEmpProcedure>();
            this.JJMFEmpProcedures1 = new HashSet<JJMFEmpProcedure>();
            this.JJMFEmpTaskDailyDisplays = new HashSet<JJMFEmpTaskDailyDisplay>();
            this.JJMFEmpTaskDailyDisplays1 = new HashSet<JJMFEmpTaskDailyDisplay>();
            this.JJMFEmpTaskDailyRecords = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFEmpTaskDailyRecords1 = new HashSet<JJMFEmpTaskDailyRecord>();
            this.JJMFProcedures = new HashSet<JJMFProcedure>();
            this.JJMFProcedures1 = new HashSet<JJMFProcedure>();
            this.JJMFTasks = new HashSet<JJMFTask>();
            this.JJMFTasks1 = new HashSet<JJMFTask>();
            this.JJMFTaskCals = new HashSet<JJMFTaskCal>();
            this.JJMFTaskCals1 = new HashSet<JJMFTaskCal>();
            this.JJMFTaskCalItems = new HashSet<JJMFTaskCalItem>();
            this.JJMFTaskCalItems1 = new HashSet<JJMFTaskCalItem>();
            this.JJMFTaskInternalProcs = new HashSet<JJMFTaskInternalProc>();
            this.JJMFTaskInternalProcs1 = new HashSet<JJMFTaskInternalProc>();
        }
    
        public string ID { get; set; }
        public Nullable<System.Guid> LangID { get; set; }
        public string UserName { get; set; }
        public string DisplayName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public Nullable<System.Guid> UserType { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsAdmin { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ExpiredDT { get; set; }
        public Nullable<System.DateTime> LastLogonDT { get; set; }
        public Nullable<System.Guid> EID { get; set; }
        public Nullable<int> MaxTimeOut { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAnnualLeaveCondition> InfoFabAnnualLeaveConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAnnualLeaveCondition> InfoFabAnnualLeaveConditions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAttnEnv> InfoFabAttnEnvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabAttnEnv> InfoFabAttnEnvs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCatContent> InfoFabCatContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCatContent> InfoFabCatContents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCategory> InfoFabCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCategory> InfoFabCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCode> InfoFabCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCode> InfoFabCodes1 { get; set; }
        public virtual InfoFabCode InfoFabCode { get; set; }
        public virtual InfoFabCode InfoFabCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabColumn> InfoFabColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabColumn> InfoFabColumns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabColumnsSetting> InfoFabColumnsSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabColumnsSetting> InfoFabColumnsSettings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContents2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpDeputy> InfoFabEmpDeputies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpDeputy> InfoFabEmpDeputies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmployee> InfoFabEmployees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOrg> InfoFabEmpOrgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOrg> InfoFabEmpOrgs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpProCert> InfoFabEmpProCerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpProCert> InfoFabEmpProCerts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabENV> InfoFabENVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabENV> InfoFabENVs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabENVItem> InfoFabENVItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabENVItem> InfoFabENVItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabForgotPWD> InfoFabForgotPWDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabForgotPWD> InfoFabForgotPWDs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabJobScheduler> InfoFabJobSchedulers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabJobScheduler> InfoFabJobSchedulers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabLangMapping> InfoFabLangMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabLangMapping> InfoFabLangMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabMessage> InfoFabMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabMessage> InfoFabMessages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabMessageContent> InfoFabMessageContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabMessageContent> InfoFabMessageContents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabNotify> InfoFabNotifies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabNotify> InfoFabNotifies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabNotify> InfoFabNotifies2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOrganization> InfoFabOrganizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOrganization> InfoFabOrganizations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOrgEnv> InfoFabOrgEnvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOrgEnv> InfoFabOrgEnvs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPersonal> InfoFabPersonals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPersonal> InfoFabPersonals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProCert> InfoFabProCerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProCert> InfoFabProCerts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRole> InfoFabRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRole> InfoFabRoles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRoleAuth> InfoFabRoleAuths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRoleAuth> InfoFabRoleAuths1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRoleUser> InfoFabRoleUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRoleUser> InfoFabRoleUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabRoleUser> InfoFabRoleUsers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTable> InfoFabTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTable> InfoFabTables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabType> InfoFabTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabType> InfoFabTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeave> InfoFabEmpLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeave> InfoFabEmpLeaves1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeaveDay> InfoFabEmpLeaveDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeaveDay> InfoFabEmpLeaveDays1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeaveDaysControl> InfoFabEmpLeaveDaysControls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpLeaveDaysControl> InfoFabEmpLeaveDaysControls1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOvertime> InfoFabEmpOvertimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOvertime> InfoFabEmpOvertimes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpSkill> InfoFabEmpSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpSkill> InfoFabEmpSkills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabLeaveCode> InfoFabLeaveCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabLeaveCode> InfoFabLeaveCodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOffDay> InfoFabOffDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOffDay> InfoFabOffDays1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOvertimeCode> InfoFabOvertimeCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabOvertimeCode> InfoFabOvertimeCodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPayControl> InfoFabPayControls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPayControl> InfoFabPayControls1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPayPeriod> InfoFabPayPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabPayPeriod> InfoFabPayPeriods1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProCertSkill> InfoFabProCertSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabProCertSkill> InfoFabProCertSkills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabSkill> InfoFabSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabSkill> InfoFabSkills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabSkillType> InfoFabSkillTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabSkillType> InfoFabSkillTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskEnv> InfoFabTaskEnvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTaskEnv> InfoFabTaskEnvs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUser> InfoFabUser1 { get; set; }
        public virtual InfoFabUser InfoFabUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUser> InfoFabUser11 { get; set; }
        public virtual InfoFabUser InfoFabUser3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUserAuth> InfoFabUserAuths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUserAuth> InfoFabUserAuths1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabUserAuth> InfoFabUserAuths2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWinScheduler> InfoFabWinSchedulers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWinScheduler> InfoFabWinSchedulers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkCode> InfoFabWorkCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkCode> InfoFabWorkCodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkGroup> InfoFabWorkGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkGroup> InfoFabWorkGroups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkPattern> InfoFabWorkPatterns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkPattern> InfoFabWorkPatterns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpProcedure> JJMFEmpProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpProcedure> JJMFEmpProcedures1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyDisplay> JJMFEmpTaskDailyDisplays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyDisplay> JJMFEmpTaskDailyDisplays1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFEmpTaskDailyRecord> JJMFEmpTaskDailyRecords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFProcedure> JJMFProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFProcedure> JJMFProcedures1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTask> JJMFTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTask> JJMFTasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTaskCal> JJMFTaskCals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTaskCal> JJMFTaskCals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTaskCalItem> JJMFTaskCalItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTaskCalItem> JJMFTaskCalItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTaskInternalProc> JJMFTaskInternalProcs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTaskInternalProc> JJMFTaskInternalProcs1 { get; set; }
    }
}
