//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabContent()
        {
            this.InfoFabCatContents = new HashSet<InfoFabCatContent>();
            this.InfoFabContent1 = new HashSet<InfoFabContent>();
            this.InfoFabTables = new HashSet<InfoFabTable>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> FileType { get; set; }
        public string FilePath { get; set; }
        public string ContentName { get; set; }
        public string AliasName { get; set; }
        public string DisplayText { get; set; }
        public string Description { get; set; }
        public string LinkPath { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public string Area { get; set; }
        public Nullable<System.Guid> PrgType { get; set; }
        public Nullable<System.Guid> ContentStatus { get; set; }
        public Nullable<System.Guid> FunctionSet { get; set; }
        public string IconPath { get; set; }
        public string Owner { get; set; }
        public Nullable<int> Seq { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ExpiredDT { get; set; }
        public bool IsMobility { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabCatContent> InfoFabCatContents { get; set; }
        public virtual InfoFabCode InfoFabCode { get; set; }
        public virtual InfoFabCode InfoFabCode1 { get; set; }
        public virtual InfoFabCode InfoFabCode2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabContent> InfoFabContent1 { get; set; }
        public virtual InfoFabContent InfoFabContent2 { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        public virtual InfoFabUser InfoFabUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabTable> InfoFabTables { get; set; }
    }
}
