//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFabWorkGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFabWorkGroup()
        {
            this.InfoFabEmpOrgs = new HashSet<InfoFabEmpOrg>();
            this.InfoFabWorkPatterns = new HashSet<InfoFabWorkPattern>();
        }
    
        public System.Guid ID { get; set; }
        public string WorkGroupCode { get; set; }
        public string WorkGroupName { get; set; }
        public System.DateTime BeginDate { get; set; }
        public bool IsFollowCalendar { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
        public int DaysInCycle { get; set; }
        public bool IsResetNextMonth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabEmpOrg> InfoFabEmpOrgs { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoFabWorkPattern> InfoFabWorkPatterns { get; set; }
    }
}
