//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JJMFEmpTaskDailyRecord
    {
        public System.Guid ID { get; set; }
        public System.Guid EmpID { get; set; }
        public System.DateTime WorkDate { get; set; }
        public System.Guid JJMFTaskID { get; set; }
        public System.Guid JJMFProcID { get; set; }
        public System.Guid Frequency { get; set; }
        public Nullable<decimal> CalWorkHours { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> OTReason { get; set; }
        public string OTReasonRemark { get; set; }
        public Nullable<System.Guid> ApproveStatus { get; set; }
        public Nullable<System.Guid> WorkCodeID { get; set; }
        public Nullable<System.Guid> ReasonCode { get; set; }
        public Nullable<System.Guid> FPID { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        public virtual InfoFabCode InfoFabCode { get; set; }
        public virtual InfoFabCode InfoFabCode1 { get; set; }
        public virtual InfoFabCode InfoFabCode2 { get; set; }
        public virtual InfoFabCode InfoFabCode3 { get; set; }
        public virtual InfoFabEmployee InfoFabEmployee { get; set; }
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        public virtual InfoFabWorkCode InfoFabWorkCode { get; set; }
        public virtual JJMFProcedure JJMFProcedure { get; set; }
        public virtual JJMFTask JJMFTask { get; set; }
    }
}
