//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JJMFTaskCal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JJMFTaskCal()
        {
            this.JJMFTaskCalItems = new HashSet<JJMFTaskCalItem>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid JJMFTaskID { get; set; }
        public System.Guid JJMFProcID { get; set; }
        public Nullable<bool> IsAllDay { get; set; }
        public Nullable<System.DateTime> CalSDate { get; set; }
        public Nullable<System.DateTime> CalEDate { get; set; }
        public Nullable<decimal> CalQty { get; set; }
        public string CalUnit { get; set; }
        public Nullable<System.DateTime> ActualSDate { get; set; }
        public Nullable<System.DateTime> ActualEDate { get; set; }
        public Nullable<decimal> ActualQty { get; set; }
        public string ActualUnit { get; set; }
        public string InitUID { get; set; }
        public System.DateTime InitDT { get; set; }
        public string ModifiedUID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        public virtual InfoFabUser InfoFabUser { get; set; }
        public virtual InfoFabUser InfoFabUser1 { get; set; }
        public virtual JJMFProcedure JJMFProcedure { get; set; }
        public virtual JJMFTask JJMFTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JJMFTaskCalItem> JJMFTaskCalItems { get; set; }
    }
}
