//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using L10N;
    public partial class LogonModel
    {
        [Display(ResourceType = typeof(L10N.Resource), Name = "Account")]
        [Required]
        public string Account { get; set; }
        [Display(ResourceType = typeof(L10N.Resource), Name = "Password")]
        [DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }
        [Display(ResourceType = typeof(L10N.Resource), Name = "Remember")]
        [Required]
        public bool Remember { get; set; }
    }
}
