//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysassembly
    {
        public string name { get; set; }
        public Nullable<int> principal_id { get; set; }
        public int assembly_id { get; set; }
        public string clr_name { get; set; }
        public Nullable<byte> permission_set { get; set; }
        public string permission_set_desc { get; set; }
        public bool is_visible { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modify_date { get; set; }
        public Nullable<bool> is_user_defined { get; set; }
    }
}
