//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysassembly_modules
    {
        public int object_id { get; set; }
        public int assembly_id { get; set; }
        public string assembly_class { get; set; }
        public string assembly_method { get; set; }
        public Nullable<bool> null_on_null_input { get; set; }
        public Nullable<int> execute_as_principal_id { get; set; }
    }
}
