//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysasymmetric_keys
    {
        public string name { get; set; }
        public Nullable<int> principal_id { get; set; }
        public int asymmetric_key_id { get; set; }
        public string pvt_key_encryption_type { get; set; }
        public string pvt_key_encryption_type_desc { get; set; }
        public byte[] thumbprint { get; set; }
        public string algorithm { get; set; }
        public string algorithm_desc { get; set; }
        public int key_length { get; set; }
        public byte[] sid { get; set; }
        public string string_sid { get; set; }
        public byte[] public_key { get; set; }
        public string attested_by { get; set; }
        public string provider_type { get; set; }
        public Nullable<System.Guid> cryptographic_provider_guid { get; set; }
    }
}
