//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysconversation_endpoints
    {
        public System.Guid conversation_handle { get; set; }
        public System.Guid conversation_id { get; set; }
        public bool is_initiator { get; set; }
        public int service_contract_id { get; set; }
        public System.Guid conversation_group_id { get; set; }
        public int service_id { get; set; }
        public System.DateTime lifetime { get; set; }
        public string state { get; set; }
        public string state_desc { get; set; }
        public string far_service { get; set; }
        public string far_broker_instance { get; set; }
        public int principal_id { get; set; }
        public int far_principal_id { get; set; }
        public System.Guid outbound_session_key_identifier { get; set; }
        public System.Guid inbound_session_key_identifier { get; set; }
        public System.DateTime security_timestamp { get; set; }
        public System.DateTime dialog_timer { get; set; }
        public long send_sequence { get; set; }
        public byte[] last_send_tran_id { get; set; }
        public long end_dialog_sequence { get; set; }
        public long receive_sequence { get; set; }
        public int receive_sequence_frag { get; set; }
        public long system_sequence { get; set; }
        public long first_out_of_order_sequence { get; set; }
        public long last_out_of_order_sequence { get; set; }
        public int last_out_of_order_frag { get; set; }
        public bool is_system { get; set; }
        public byte priority { get; set; }
    }
}
