//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syscertificate
    {
        public string name { get; set; }
        public int certificate_id { get; set; }
        public Nullable<int> principal_id { get; set; }
        public string pvt_key_encryption_type { get; set; }
        public string pvt_key_encryption_type_desc { get; set; }
        public Nullable<bool> is_active_for_begin_dialog { get; set; }
        public string issuer_name { get; set; }
        public string cert_serial_number { get; set; }
        public byte[] sid { get; set; }
        public string string_sid { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public byte[] thumbprint { get; set; }
        public string attested_by { get; set; }
        public Nullable<System.DateTime> pvt_key_last_backup_date { get; set; }
    }
}
