//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syscomputed_columns
    {
        public int object_id { get; set; }
        public string name { get; set; }
        public int column_id { get; set; }
        public byte system_type_id { get; set; }
        public int user_type_id { get; set; }
        public short max_length { get; set; }
        public byte precision { get; set; }
        public byte scale { get; set; }
        public string collation_name { get; set; }
        public Nullable<bool> is_nullable { get; set; }
        public bool is_ansi_padded { get; set; }
        public bool is_rowguidcol { get; set; }
        public bool is_identity { get; set; }
        public bool is_filestream { get; set; }
        public Nullable<bool> is_replicated { get; set; }
        public Nullable<bool> is_non_sql_subscribed { get; set; }
        public Nullable<bool> is_merge_published { get; set; }
        public Nullable<bool> is_dts_replicated { get; set; }
        public bool is_xml_document { get; set; }
        public int xml_collection_id { get; set; }
        public int default_object_id { get; set; }
        public int rule_object_id { get; set; }
        public string definition { get; set; }
        public bool uses_database_collation { get; set; }
        public bool is_persisted { get; set; }
        public bool is_computed { get; set; }
        public bool is_sparse { get; set; }
        public bool is_column_set { get; set; }
    }
}
