//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_exec_sessions
    {
        public short session_id { get; set; }
        public System.DateTime login_time { get; set; }
        public string host_name { get; set; }
        public string program_name { get; set; }
        public Nullable<int> host_process_id { get; set; }
        public Nullable<int> client_version { get; set; }
        public string client_interface_name { get; set; }
        public byte[] security_id { get; set; }
        public string login_name { get; set; }
        public string nt_domain { get; set; }
        public string nt_user_name { get; set; }
        public string status { get; set; }
        public byte[] context_info { get; set; }
        public int cpu_time { get; set; }
        public int memory_usage { get; set; }
        public int total_scheduled_time { get; set; }
        public int total_elapsed_time { get; set; }
        public int endpoint_id { get; set; }
        public System.DateTime last_request_start_time { get; set; }
        public Nullable<System.DateTime> last_request_end_time { get; set; }
        public long reads { get; set; }
        public long writes { get; set; }
        public long logical_reads { get; set; }
        public bool is_user_process { get; set; }
        public int text_size { get; set; }
        public string language { get; set; }
        public string date_format { get; set; }
        public short date_first { get; set; }
        public bool quoted_identifier { get; set; }
        public bool arithabort { get; set; }
        public bool ansi_null_dflt_on { get; set; }
        public bool ansi_defaults { get; set; }
        public bool ansi_warnings { get; set; }
        public bool ansi_padding { get; set; }
        public bool ansi_nulls { get; set; }
        public bool concat_null_yields_null { get; set; }
        public short transaction_isolation_level { get; set; }
        public int lock_timeout { get; set; }
        public int deadlock_priority { get; set; }
        public long row_count { get; set; }
        public int prev_error { get; set; }
        public byte[] original_security_id { get; set; }
        public string original_login_name { get; set; }
        public Nullable<System.DateTime> last_successful_logon { get; set; }
        public Nullable<System.DateTime> last_unsuccessful_logon { get; set; }
        public Nullable<long> unsuccessful_logons { get; set; }
        public int group_id { get; set; }
    }
}
