//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_fts_outstanding_batches
    {
        public int database_id { get; set; }
        public int catalog_id { get; set; }
        public int table_id { get; set; }
        public int batch_id { get; set; }
        public byte[] memory_address { get; set; }
        public byte[] crawl_memory_address { get; set; }
        public byte[] memregion_memory_address { get; set; }
        public int hr_batch { get; set; }
        public bool is_retry_batch { get; set; }
        public int retry_hints { get; set; }
        public string retry_hints_description { get; set; }
        public long doc_failed { get; set; }
        public byte[] batch_timestamp { get; set; }
    }
}
