//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_xe_objects
    {
        public string name { get; set; }
        public string object_type { get; set; }
        public System.Guid package_guid { get; set; }
        public string description { get; set; }
        public Nullable<int> capabilities { get; set; }
        public string capabilities_desc { get; set; }
        public string type_name { get; set; }
        public Nullable<System.Guid> type_package_guid { get; set; }
        public Nullable<int> type_size { get; set; }
    }
}
