//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_server_services
    {
        public string servicename { get; set; }
        public Nullable<int> startup_type { get; set; }
        public string startup_type_desc { get; set; }
        public Nullable<int> status { get; set; }
        public string status_desc { get; set; }
        public Nullable<int> process_id { get; set; }
        public Nullable<System.DateTimeOffset> last_startup_time { get; set; }
        public string service_account { get; set; }
        public string filename { get; set; }
        public string is_clustered { get; set; }
        public string cluster_nodename { get; set; }
    }
}
