//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_exec_cached_plans
    {
        public int bucketid { get; set; }
        public int refcounts { get; set; }
        public int usecounts { get; set; }
        public int size_in_bytes { get; set; }
        public byte[] memory_object_address { get; set; }
        public string cacheobjtype { get; set; }
        public string objtype { get; set; }
        public byte[] plan_handle { get; set; }
        public int pool_id { get; set; }
    }
}
