//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_tran_locks
    {
        public string resource_type { get; set; }
        public string resource_subtype { get; set; }
        public int resource_database_id { get; set; }
        public string resource_description { get; set; }
        public Nullable<long> resource_associated_entity_id { get; set; }
        public Nullable<int> resource_lock_partition { get; set; }
        public string request_mode { get; set; }
        public string request_type { get; set; }
        public string request_status { get; set; }
        public short request_reference_count { get; set; }
        public int request_lifetime { get; set; }
        public int request_session_id { get; set; }
        public int request_exec_context_id { get; set; }
        public int request_request_id { get; set; }
        public string request_owner_type { get; set; }
        public Nullable<long> request_owner_id { get; set; }
        public Nullable<System.Guid> request_owner_guid { get; set; }
        public string request_owner_lockspace_id { get; set; }
        public byte[] lock_owner_address { get; set; }
    }
}
