//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_waiting_tasks
    {
        public byte[] waiting_task_address { get; set; }
        public Nullable<short> session_id { get; set; }
        public Nullable<int> exec_context_id { get; set; }
        public Nullable<long> wait_duration_ms { get; set; }
        public string wait_type { get; set; }
        public byte[] resource_address { get; set; }
        public byte[] blocking_task_address { get; set; }
        public Nullable<short> blocking_session_id { get; set; }
        public Nullable<int> blocking_exec_context_id { get; set; }
        public string resource_description { get; set; }
    }
}
