//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_dispatchers
    {
        public byte[] dispatcher_pool_address { get; set; }
        public byte[] task_address { get; set; }
        public string state { get; set; }
        public Nullable<long> wait_duration { get; set; }
        public Nullable<long> current_item_duration { get; set; }
        public long items_processed { get; set; }
        public Nullable<int> fade_end_time { get; set; }
    }
}
