//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_db_missing_index_group_stats
    {
        public int group_handle { get; set; }
        public long unique_compiles { get; set; }
        public long user_seeks { get; set; }
        public long user_scans { get; set; }
        public Nullable<System.DateTime> last_user_seek { get; set; }
        public Nullable<System.DateTime> last_user_scan { get; set; }
        public Nullable<double> avg_total_user_cost { get; set; }
        public Nullable<double> avg_user_impact { get; set; }
        public long system_seeks { get; set; }
        public long system_scans { get; set; }
        public Nullable<System.DateTime> last_system_seek { get; set; }
        public Nullable<System.DateTime> last_system_scan { get; set; }
        public Nullable<double> avg_total_system_cost { get; set; }
        public Nullable<double> avg_system_impact { get; set; }
    }
}
