//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_memory_brokers
    {
        public int pool_id { get; set; }
        public string memory_broker_type { get; set; }
        public long allocations_kb { get; set; }
        public long allocations_kb_per_sec { get; set; }
        public long predicted_allocations_kb { get; set; }
        public long target_allocations_kb { get; set; }
        public long future_allocations_kb { get; set; }
        public long overall_limit_kb { get; set; }
        public string last_notification { get; set; }
    }
}
