//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_tasks
    {
        public byte[] task_address { get; set; }
        public string task_state { get; set; }
        public Nullable<int> context_switches_count { get; set; }
        public Nullable<int> pending_io_count { get; set; }
        public Nullable<long> pending_io_byte_count { get; set; }
        public Nullable<int> pending_io_byte_average { get; set; }
        public int scheduler_id { get; set; }
        public Nullable<short> session_id { get; set; }
        public Nullable<int> exec_context_id { get; set; }
        public Nullable<int> request_id { get; set; }
        public byte[] worker_address { get; set; }
        public byte[] host_address { get; set; }
        public byte[] parent_task_address { get; set; }
    }
}
