//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_exec_background_job_queue
    {
        public System.DateTime time_queued { get; set; }
        public int job_id { get; set; }
        public int database_id { get; set; }
        public int object_id1 { get; set; }
        public int object_id2 { get; set; }
        public int object_id3 { get; set; }
        public int object_id4 { get; set; }
        public Nullable<int> error_code { get; set; }
        public short request_type { get; set; }
        public short retry_count { get; set; }
        public short in_progress { get; set; }
        public Nullable<short> session_id { get; set; }
    }
}
