//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdatabas
    {
        public string name { get; set; }
        public int database_id { get; set; }
        public Nullable<int> source_database_id { get; set; }
        public byte[] owner_sid { get; set; }
        public System.DateTime create_date { get; set; }
        public byte compatibility_level { get; set; }
        public string collation_name { get; set; }
        public Nullable<byte> user_access { get; set; }
        public string user_access_desc { get; set; }
        public Nullable<bool> is_read_only { get; set; }
        public bool is_auto_close_on { get; set; }
        public Nullable<bool> is_auto_shrink_on { get; set; }
        public Nullable<byte> state { get; set; }
        public string state_desc { get; set; }
        public Nullable<bool> is_in_standby { get; set; }
        public Nullable<bool> is_cleanly_shutdown { get; set; }
        public Nullable<bool> is_supplemental_logging_enabled { get; set; }
        public Nullable<byte> snapshot_isolation_state { get; set; }
        public string snapshot_isolation_state_desc { get; set; }
        public Nullable<bool> is_read_committed_snapshot_on { get; set; }
        public Nullable<byte> recovery_model { get; set; }
        public string recovery_model_desc { get; set; }
        public Nullable<byte> page_verify_option { get; set; }
        public string page_verify_option_desc { get; set; }
        public Nullable<bool> is_auto_create_stats_on { get; set; }
        public Nullable<bool> is_auto_update_stats_on { get; set; }
        public Nullable<bool> is_auto_update_stats_async_on { get; set; }
        public Nullable<bool> is_ansi_null_default_on { get; set; }
        public Nullable<bool> is_ansi_nulls_on { get; set; }
        public Nullable<bool> is_ansi_padding_on { get; set; }
        public Nullable<bool> is_ansi_warnings_on { get; set; }
        public Nullable<bool> is_arithabort_on { get; set; }
        public Nullable<bool> is_concat_null_yields_null_on { get; set; }
        public Nullable<bool> is_numeric_roundabort_on { get; set; }
        public Nullable<bool> is_quoted_identifier_on { get; set; }
        public Nullable<bool> is_recursive_triggers_on { get; set; }
        public Nullable<bool> is_cursor_close_on_commit_on { get; set; }
        public Nullable<bool> is_local_cursor_default { get; set; }
        public Nullable<bool> is_fulltext_enabled { get; set; }
        public Nullable<bool> is_trustworthy_on { get; set; }
        public Nullable<bool> is_db_chaining_on { get; set; }
        public Nullable<bool> is_parameterization_forced { get; set; }
        public bool is_master_key_encrypted_by_server { get; set; }
        public bool is_published { get; set; }
        public bool is_subscribed { get; set; }
        public bool is_merge_published { get; set; }
        public bool is_distributor { get; set; }
        public bool is_sync_with_backup { get; set; }
        public System.Guid service_broker_guid { get; set; }
        public bool is_broker_enabled { get; set; }
        public Nullable<byte> log_reuse_wait { get; set; }
        public string log_reuse_wait_desc { get; set; }
        public bool is_date_correlation_on { get; set; }
        public bool is_cdc_enabled { get; set; }
        public Nullable<bool> is_encrypted { get; set; }
        public Nullable<bool> is_honor_broker_priority_on { get; set; }
    }
}
