//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_dispatcher_pools
    {
        public byte[] dispatcher_pool_address { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public int dispatcher_count { get; set; }
        public int dispatcher_ideal_count { get; set; }
        public int dispatcher_timeout_ms { get; set; }
        public int dispatcher_waiting_count { get; set; }
        public int queue_length { get; set; }
    }
}
