//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdatabase_mirroring
    {
        public int database_id { get; set; }
        public Nullable<System.Guid> mirroring_guid { get; set; }
        public Nullable<byte> mirroring_state { get; set; }
        public string mirroring_state_desc { get; set; }
        public Nullable<byte> mirroring_role { get; set; }
        public string mirroring_role_desc { get; set; }
        public Nullable<int> mirroring_role_sequence { get; set; }
        public Nullable<byte> mirroring_safety_level { get; set; }
        public string mirroring_safety_level_desc { get; set; }
        public Nullable<int> mirroring_safety_sequence { get; set; }
        public string mirroring_partner_name { get; set; }
        public string mirroring_partner_instance { get; set; }
        public string mirroring_witness_name { get; set; }
        public Nullable<byte> mirroring_witness_state { get; set; }
        public string mirroring_witness_state_desc { get; set; }
        public Nullable<decimal> mirroring_failover_lsn { get; set; }
        public Nullable<int> mirroring_connection_timeout { get; set; }
        public Nullable<int> mirroring_redo_queue { get; set; }
        public string mirroring_redo_queue_type { get; set; }
        public Nullable<decimal> mirroring_end_of_log_lsn { get; set; }
        public Nullable<decimal> mirroring_replication_lsn { get; set; }
    }
}
