//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_loaded_modules
    {
        public byte[] base_address { get; set; }
        public string file_version { get; set; }
        public string product_version { get; set; }
        public Nullable<bool> debug { get; set; }
        public Nullable<bool> patched { get; set; }
        public Nullable<bool> prerelease { get; set; }
        public Nullable<bool> private_build { get; set; }
        public Nullable<bool> special_build { get; set; }
        public Nullable<int> language { get; set; }
        public string company { get; set; }
        public string description { get; set; }
        public string name { get; set; }
    }
}
