//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_xe_sessions
    {
        public byte[] address { get; set; }
        public string name { get; set; }
        public int pending_buffers { get; set; }
        public int total_regular_buffers { get; set; }
        public long regular_buffer_size { get; set; }
        public int total_large_buffers { get; set; }
        public long large_buffer_size { get; set; }
        public long total_buffer_size { get; set; }
        public int buffer_policy_flags { get; set; }
        public string buffer_policy_desc { get; set; }
        public int flags { get; set; }
        public string flag_desc { get; set; }
        public int dropped_event_count { get; set; }
        public int dropped_buffer_count { get; set; }
        public int blocked_event_fire_time { get; set; }
        public System.DateTime create_time { get; set; }
        public int largest_event_dropped_size { get; set; }
    }
}
