//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_io_pending_io_requests
    {
        public byte[] io_completion_request_address { get; set; }
        public string io_type { get; set; }
        public long io_pending_ms_ticks { get; set; }
        public int io_pending { get; set; }
        public byte[] io_completion_routine_address { get; set; }
        public byte[] io_user_data_address { get; set; }
        public byte[] scheduler_address { get; set; }
        public byte[] io_handle { get; set; }
        public long io_offset { get; set; }
    }
}
