//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_exec_requests
    {
        public short session_id { get; set; }
        public int request_id { get; set; }
        public System.DateTime start_time { get; set; }
        public string status { get; set; }
        public string command { get; set; }
        public byte[] sql_handle { get; set; }
        public Nullable<int> statement_start_offset { get; set; }
        public Nullable<int> statement_end_offset { get; set; }
        public byte[] plan_handle { get; set; }
        public short database_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.Guid> connection_id { get; set; }
        public Nullable<short> blocking_session_id { get; set; }
        public string wait_type { get; set; }
        public int wait_time { get; set; }
        public string last_wait_type { get; set; }
        public string wait_resource { get; set; }
        public int open_transaction_count { get; set; }
        public int open_resultset_count { get; set; }
        public long transaction_id { get; set; }
        public byte[] context_info { get; set; }
        public float percent_complete { get; set; }
        public long estimated_completion_time { get; set; }
        public int cpu_time { get; set; }
        public int total_elapsed_time { get; set; }
        public Nullable<int> scheduler_id { get; set; }
        public byte[] task_address { get; set; }
        public long reads { get; set; }
        public long writes { get; set; }
        public long logical_reads { get; set; }
        public int text_size { get; set; }
        public string language { get; set; }
        public string date_format { get; set; }
        public short date_first { get; set; }
        public bool quoted_identifier { get; set; }
        public bool arithabort { get; set; }
        public bool ansi_null_dflt_on { get; set; }
        public bool ansi_defaults { get; set; }
        public bool ansi_warnings { get; set; }
        public bool ansi_padding { get; set; }
        public bool ansi_nulls { get; set; }
        public bool concat_null_yields_null { get; set; }
        public short transaction_isolation_level { get; set; }
        public int lock_timeout { get; set; }
        public int deadlock_priority { get; set; }
        public long row_count { get; set; }
        public int prev_error { get; set; }
        public int nest_level { get; set; }
        public int granted_query_memory { get; set; }
        public bool executing_managed_code { get; set; }
        public int group_id { get; set; }
        public byte[] query_hash { get; set; }
        public byte[] query_plan_hash { get; set; }
    }
}
