//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_db_partition_stats
    {
        public long partition_id { get; set; }
        public int object_id { get; set; }
        public int index_id { get; set; }
        public int partition_number { get; set; }
        public long in_row_data_page_count { get; set; }
        public long in_row_used_page_count { get; set; }
        public long in_row_reserved_page_count { get; set; }
        public long lob_used_page_count { get; set; }
        public long lob_reserved_page_count { get; set; }
        public long row_overflow_used_page_count { get; set; }
        public long row_overflow_reserved_page_count { get; set; }
        public long used_page_count { get; set; }
        public long reserved_page_count { get; set; }
        public long row_count { get; set; }
    }
}
