//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_spinlock_stats
    {
        public string name { get; set; }
        public Nullable<long> collisions { get; set; }
        public Nullable<long> spins { get; set; }
        public Nullable<float> spins_per_collision { get; set; }
        public Nullable<long> sleep_time { get; set; }
        public Nullable<int> backoffs { get; set; }
    }
}
