//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_memory_cache_clock_hands
    {
        public byte[] cache_address { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string clock_hand { get; set; }
        public string clock_status { get; set; }
        public long rounds_count { get; set; }
        public long removed_all_rounds_count { get; set; }
        public long updated_last_round_count { get; set; }
        public long removed_last_round_count { get; set; }
        public long last_tick_time { get; set; }
        public long round_start_time { get; set; }
        public long last_round_start_time { get; set; }
    }
}
