//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_memory_cache_entries
    {
        public byte[] cache_address { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public byte[] entry_address { get; set; }
        public byte[] entry_data_address { get; set; }
        public int in_use_count { get; set; }
        public bool is_dirty { get; set; }
        public int disk_ios_count { get; set; }
        public int context_switches_count { get; set; }
        public int original_cost { get; set; }
        public int current_cost { get; set; }
        public byte[] memory_object_address { get; set; }
        public long pages_allocated_count { get; set; }
        public string entry_data { get; set; }
        public Nullable<int> pool_id { get; set; }
    }
}
