//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_exec_background_job_queue_stats
    {
        public int queue_max_len { get; set; }
        public int enqueued_count { get; set; }
        public int started_count { get; set; }
        public int ended_count { get; set; }
        public int failed_lock_count { get; set; }
        public int failed_other_count { get; set; }
        public int failed_giveup_count { get; set; }
        public int enqueue_failed_full_count { get; set; }
        public int enqueue_failed_duplicate_count { get; set; }
        public int elapsed_avg_ms { get; set; }
        public int elapsed_max_ms { get; set; }
    }
}
