//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_exec_query_stats
    {
        public byte[] sql_handle { get; set; }
        public int statement_start_offset { get; set; }
        public int statement_end_offset { get; set; }
        public long plan_generation_num { get; set; }
        public byte[] plan_handle { get; set; }
        public System.DateTime creation_time { get; set; }
        public System.DateTime last_execution_time { get; set; }
        public long execution_count { get; set; }
        public long total_worker_time { get; set; }
        public long last_worker_time { get; set; }
        public long min_worker_time { get; set; }
        public long max_worker_time { get; set; }
        public long total_physical_reads { get; set; }
        public long last_physical_reads { get; set; }
        public long min_physical_reads { get; set; }
        public long max_physical_reads { get; set; }
        public long total_logical_writes { get; set; }
        public long last_logical_writes { get; set; }
        public long min_logical_writes { get; set; }
        public long max_logical_writes { get; set; }
        public long total_logical_reads { get; set; }
        public long last_logical_reads { get; set; }
        public long min_logical_reads { get; set; }
        public long max_logical_reads { get; set; }
        public long total_clr_time { get; set; }
        public long last_clr_time { get; set; }
        public long min_clr_time { get; set; }
        public long max_clr_time { get; set; }
        public long total_elapsed_time { get; set; }
        public long last_elapsed_time { get; set; }
        public long min_elapsed_time { get; set; }
        public long max_elapsed_time { get; set; }
        public byte[] query_hash { get; set; }
        public byte[] query_plan_hash { get; set; }
        public long total_rows { get; set; }
        public long last_rows { get; set; }
        public long min_rows { get; set; }
        public long max_rows { get; set; }
    }
}
