//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_resource_governor_workload_groups
    {
        public int group_id { get; set; }
        public string name { get; set; }
        public int pool_id { get; set; }
        public System.DateTime statistics_start_time { get; set; }
        public long total_request_count { get; set; }
        public long total_queued_request_count { get; set; }
        public int active_request_count { get; set; }
        public int queued_request_count { get; set; }
        public long total_cpu_limit_violation_count { get; set; }
        public long total_cpu_usage_ms { get; set; }
        public long max_request_cpu_time_ms { get; set; }
        public int blocked_task_count { get; set; }
        public long total_lock_wait_count { get; set; }
        public long total_lock_wait_time_ms { get; set; }
        public long total_query_optimization_count { get; set; }
        public long total_suboptimal_plan_generation_count { get; set; }
        public long total_reduced_memgrant_count { get; set; }
        public long max_request_grant_memory_kb { get; set; }
        public long active_parallel_thread_count { get; set; }
        public string importance { get; set; }
        public int request_max_memory_grant_percent { get; set; }
        public int request_max_cpu_time_sec { get; set; }
        public int request_memory_grant_timeout_sec { get; set; }
        public int group_max_requests { get; set; }
        public int max_dop { get; set; }
    }
}
