//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_db_index_usage_stats
    {
        public short database_id { get; set; }
        public int object_id { get; set; }
        public int index_id { get; set; }
        public long user_seeks { get; set; }
        public long user_scans { get; set; }
        public long user_lookups { get; set; }
        public long user_updates { get; set; }
        public Nullable<System.DateTime> last_user_seek { get; set; }
        public Nullable<System.DateTime> last_user_scan { get; set; }
        public Nullable<System.DateTime> last_user_lookup { get; set; }
        public Nullable<System.DateTime> last_user_update { get; set; }
        public long system_seeks { get; set; }
        public long system_scans { get; set; }
        public long system_lookups { get; set; }
        public long system_updates { get; set; }
        public Nullable<System.DateTime> last_system_seek { get; set; }
        public Nullable<System.DateTime> last_system_scan { get; set; }
        public Nullable<System.DateTime> last_system_lookup { get; set; }
        public Nullable<System.DateTime> last_system_update { get; set; }
    }
}
