//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_memory_allocations
    {
        public byte[] memory_allocation_address { get; set; }
        public long size_in_bytes { get; set; }
        public System.DateTime creation_time { get; set; }
        public byte[] memory_object_address { get; set; }
        public short memory_node_id { get; set; }
        public byte[] allocator_stack_address { get; set; }
        public string source_file { get; set; }
        public int line_num { get; set; }
        public int sequence_num { get; set; }
        public int tag { get; set; }
    }
}
