//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_fts_fdhosts
    {
        public int fdhost_id { get; set; }
        public string fdhost_name { get; set; }
        public int fdhost_process_id { get; set; }
        public string fdhost_type { get; set; }
        public int max_thread { get; set; }
        public int batch_count { get; set; }
    }
}
