//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_tran_session_transactions
    {
        public int session_id { get; set; }
        public long transaction_id { get; set; }
        public byte[] transaction_descriptor { get; set; }
        public int enlist_count { get; set; }
        public bool is_user_transaction { get; set; }
        public bool is_local { get; set; }
        public bool is_enlisted { get; set; }
        public bool is_bound { get; set; }
    }
}
