//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_tran_database_transactions
    {
        public long transaction_id { get; set; }
        public int database_id { get; set; }
        public Nullable<System.DateTime> database_transaction_begin_time { get; set; }
        public int database_transaction_type { get; set; }
        public int database_transaction_state { get; set; }
        public int database_transaction_status { get; set; }
        public int database_transaction_status2 { get; set; }
        public long database_transaction_log_record_count { get; set; }
        public int database_transaction_replicate_record_count { get; set; }
        public long database_transaction_log_bytes_used { get; set; }
        public long database_transaction_log_bytes_reserved { get; set; }
        public int database_transaction_log_bytes_used_system { get; set; }
        public int database_transaction_log_bytes_reserved_system { get; set; }
        public Nullable<decimal> database_transaction_begin_lsn { get; set; }
        public Nullable<decimal> database_transaction_last_lsn { get; set; }
        public Nullable<decimal> database_transaction_most_recent_savepoint_lsn { get; set; }
        public Nullable<decimal> database_transaction_commit_lsn { get; set; }
        public Nullable<decimal> database_transaction_last_rollback_lsn { get; set; }
        public Nullable<decimal> database_transaction_next_undo_lsn { get; set; }
    }
}
