//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_tran_active_transactions
    {
        public long transaction_id { get; set; }
        public string name { get; set; }
        public System.DateTime transaction_begin_time { get; set; }
        public int transaction_type { get; set; }
        public Nullable<System.Guid> transaction_uow { get; set; }
        public int transaction_state { get; set; }
        public int transaction_status { get; set; }
        public int transaction_status2 { get; set; }
        public int dtc_state { get; set; }
        public int dtc_status { get; set; }
        public int dtc_isolation_level { get; set; }
        public byte[] filestream_transaction_id { get; set; }
    }
}
