//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_performance_counters
    {
        public string object_name { get; set; }
        public string counter_name { get; set; }
        public string instance_name { get; set; }
        public long cntr_value { get; set; }
        public int cntr_type { get; set; }
    }
}
