//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_process_memory
    {
        public long physical_memory_in_use_kb { get; set; }
        public long large_page_allocations_kb { get; set; }
        public long locked_page_allocations_kb { get; set; }
        public long total_virtual_address_space_kb { get; set; }
        public long virtual_address_space_reserved_kb { get; set; }
        public long virtual_address_space_committed_kb { get; set; }
        public long virtual_address_space_available_kb { get; set; }
        public long page_fault_count { get; set; }
        public int memory_utilization_percentage { get; set; }
        public long available_commit_limit_kb { get; set; }
        public bool process_physical_memory_low { get; set; }
        public bool process_virtual_memory_low { get; set; }
    }
}
