//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_sys_memory
    {
        public long total_physical_memory_kb { get; set; }
        public long available_physical_memory_kb { get; set; }
        public long total_page_file_kb { get; set; }
        public long available_page_file_kb { get; set; }
        public long system_cache_kb { get; set; }
        public long kernel_paged_pool_kb { get; set; }
        public long kernel_nonpaged_pool_kb { get; set; }
        public bool system_high_memory_signal_state { get; set; }
        public bool system_low_memory_signal_state { get; set; }
        public string system_memory_state_desc { get; set; }
    }
}
