//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_memory_clerks
    {
        public byte[] memory_clerk_address { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public short memory_node_id { get; set; }
        public long single_pages_kb { get; set; }
        public long multi_pages_kb { get; set; }
        public long virtual_memory_reserved_kb { get; set; }
        public long virtual_memory_committed_kb { get; set; }
        public long awe_allocated_kb { get; set; }
        public long shared_memory_reserved_kb { get; set; }
        public long shared_memory_committed_kb { get; set; }
        public long page_size_bytes { get; set; }
        public byte[] page_allocator_address { get; set; }
        public byte[] host_address { get; set; }
    }
}
