//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_memory_objects
    {
        public byte[] memory_object_address { get; set; }
        public byte[] parent_address { get; set; }
        public int pages_allocated_count { get; set; }
        public Nullable<int> creation_options { get; set; }
        public Nullable<long> bytes_used { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public short memory_node_id { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public int page_size_in_bytes { get; set; }
        public int max_pages_allocated_count { get; set; }
        public byte[] page_allocator_address { get; set; }
        public byte[] creation_stack_address { get; set; }
        public Nullable<int> sequence_num { get; set; }
    }
}
