//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_fts_index_population
    {
        public int database_id { get; set; }
        public int catalog_id { get; set; }
        public int table_id { get; set; }
        public byte[] memory_address { get; set; }
        public int population_type { get; set; }
        public string population_type_description { get; set; }
        public bool is_clustered_index_scan { get; set; }
        public int range_count { get; set; }
        public int completed_range_count { get; set; }
        public int outstanding_batch_count { get; set; }
        public int status { get; set; }
        public string status_description { get; set; }
        public int completion_type { get; set; }
        public string completion_type_description { get; set; }
        public int worker_count { get; set; }
        public int queued_population_type { get; set; }
        public string queued_population_type_description { get; set; }
        public System.DateTime start_time { get; set; }
        public byte[] incremental_timestamp { get; set; }
    }
}
