//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_resource_governor_resource_pools
    {
        public int pool_id { get; set; }
        public string name { get; set; }
        public System.DateTime statistics_start_time { get; set; }
        public long total_cpu_usage_ms { get; set; }
        public long cache_memory_kb { get; set; }
        public long compile_memory_kb { get; set; }
        public long used_memgrant_kb { get; set; }
        public long total_memgrant_count { get; set; }
        public long total_memgrant_timeout_count { get; set; }
        public int active_memgrant_count { get; set; }
        public long active_memgrant_kb { get; set; }
        public int memgrant_waiter_count { get; set; }
        public long max_memory_kb { get; set; }
        public long used_memory_kb { get; set; }
        public long target_memory_kb { get; set; }
        public long out_of_memory_count { get; set; }
        public int min_cpu_percent { get; set; }
        public int max_cpu_percent { get; set; }
        public int min_memory_percent { get; set; }
        public int max_memory_percent { get; set; }
    }
}
