//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_os_hosts
    {
        public byte[] host_address { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public Nullable<int> enqueued_tasks_count { get; set; }
        public Nullable<int> active_tasks_count { get; set; }
        public Nullable<int> completed_ios_count { get; set; }
        public Nullable<long> completed_ios_in_bytes { get; set; }
        public Nullable<int> active_ios_count { get; set; }
        public byte[] default_memory_clerk_address { get; set; }
    }
}
