//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdatabase_files
    {
        public int file_id { get; set; }
        public Nullable<System.Guid> file_guid { get; set; }
        public byte type { get; set; }
        public string type_desc { get; set; }
        public int data_space_id { get; set; }
        public string name { get; set; }
        public string physical_name { get; set; }
        public Nullable<byte> state { get; set; }
        public string state_desc { get; set; }
        public int size { get; set; }
        public int max_size { get; set; }
        public int growth { get; set; }
        public bool is_media_read_only { get; set; }
        public bool is_read_only { get; set; }
        public bool is_sparse { get; set; }
        public bool is_percent_growth { get; set; }
        public bool is_name_reserved { get; set; }
        public Nullable<decimal> create_lsn { get; set; }
        public Nullable<decimal> drop_lsn { get; set; }
        public Nullable<decimal> read_only_lsn { get; set; }
        public Nullable<decimal> read_write_lsn { get; set; }
        public Nullable<decimal> differential_base_lsn { get; set; }
        public Nullable<System.Guid> differential_base_guid { get; set; }
        public Nullable<System.DateTime> differential_base_time { get; set; }
        public Nullable<decimal> redo_start_lsn { get; set; }
        public Nullable<System.Guid> redo_start_fork_guid { get; set; }
        public Nullable<decimal> redo_target_lsn { get; set; }
        public Nullable<System.Guid> redo_target_fork_guid { get; set; }
        public Nullable<decimal> backup_lsn { get; set; }
    }
}
