//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_fts_active_catalogs
    {
        public int database_id { get; set; }
        public int catalog_id { get; set; }
        public byte[] memory_address { get; set; }
        public string name { get; set; }
        public bool is_paused { get; set; }
        public int status { get; set; }
        public string status_description { get; set; }
        public int previous_status { get; set; }
        public string previous_status_description { get; set; }
        public int worker_count { get; set; }
        public int active_fts_index_count { get; set; }
        public int auto_population_count { get; set; }
        public int manual_population_count { get; set; }
        public int full_incremental_population_count { get; set; }
        public int row_count_in_thousands { get; set; }
        public bool is_importing { get; set; }
    }
}
