//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdm_exec_connections
    {
        public Nullable<int> session_id { get; set; }
        public Nullable<int> most_recent_session_id { get; set; }
        public System.DateTime connect_time { get; set; }
        public string net_transport { get; set; }
        public string protocol_type { get; set; }
        public Nullable<int> protocol_version { get; set; }
        public Nullable<int> endpoint_id { get; set; }
        public string encrypt_option { get; set; }
        public string auth_scheme { get; set; }
        public short node_affinity { get; set; }
        public Nullable<int> num_reads { get; set; }
        public Nullable<int> num_writes { get; set; }
        public Nullable<System.DateTime> last_read { get; set; }
        public Nullable<System.DateTime> last_write { get; set; }
        public Nullable<int> net_packet_size { get; set; }
        public string client_net_address { get; set; }
        public Nullable<int> client_tcp_port { get; set; }
        public string local_net_address { get; set; }
        public Nullable<int> local_tcp_port { get; set; }
        public System.Guid connection_id { get; set; }
        public Nullable<System.Guid> parent_connection_id { get; set; }
        public byte[] most_recent_sql_handle { get; set; }
    }
}
