//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysendpoint_webmethods
    {
        public int endpoint_id { get; set; }
        public string @namespace { get; set; }
        public string method_alias { get; set; }
        public string object_name { get; set; }
        public Nullable<byte> result_schema { get; set; }
        public string result_schema_desc { get; set; }
        public Nullable<byte> result_format { get; set; }
        public string result_format_desc { get; set; }
    }
}
