//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysfulltext_index_fragments
    {
        public int table_id { get; set; }
        public int fragment_id { get; set; }
        public int fragment_object_id { get; set; }
        public byte[] timestamp { get; set; }
        public int status { get; set; }
        public long data_size { get; set; }
        public long row_count { get; set; }
    }
}
