//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysfilegroup
    {
        public string name { get; set; }
        public int data_space_id { get; set; }
        public string type { get; set; }
        public string type_desc { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<System.Guid> filegroup_guid { get; set; }
        public Nullable<int> log_filegroup_id { get; set; }
        public Nullable<bool> is_read_only { get; set; }
    }
}
