//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysfulltext_indexes
    {
        public int object_id { get; set; }
        public int unique_index_id { get; set; }
        public Nullable<int> fulltext_catalog_id { get; set; }
        public bool is_enabled { get; set; }
        public string change_tracking_state { get; set; }
        public string change_tracking_state_desc { get; set; }
        public bool has_crawl_completed { get; set; }
        public string crawl_type { get; set; }
        public string crawl_type_desc { get; set; }
        public Nullable<System.DateTime> crawl_start_date { get; set; }
        public Nullable<System.DateTime> crawl_end_date { get; set; }
        public byte[] incremental_timestamp { get; set; }
        public Nullable<int> stoplist_id { get; set; }
        public int data_space_id { get; set; }
    }
}
