//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syshttp_endpoints
    {
        public string name { get; set; }
        public int endpoint_id { get; set; }
        public Nullable<int> principal_id { get; set; }
        public byte protocol { get; set; }
        public string protocol_desc { get; set; }
        public byte type { get; set; }
        public string type_desc { get; set; }
        public Nullable<byte> state { get; set; }
        public string state_desc { get; set; }
        public bool is_admin_endpoint { get; set; }
        public string site { get; set; }
        public string url_path { get; set; }
        public bool is_clear_port_enabled { get; set; }
        public int clear_port { get; set; }
        public bool is_ssl_port_enabled { get; set; }
        public int ssl_port { get; set; }
        public bool is_anonymous_enabled { get; set; }
        public bool is_basic_auth_enabled { get; set; }
        public bool is_digest_auth_enabled { get; set; }
        public bool is_kerberos_auth_enabled { get; set; }
        public bool is_ntlm_auth_enabled { get; set; }
        public bool is_integrated_auth_enabled { get; set; }
        public string authorization_realm { get; set; }
        public string default_logon_domain { get; set; }
        public bool is_compression_enabled { get; set; }
    }
}
