//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syspartition
    {
        public long partition_id { get; set; }
        public int object_id { get; set; }
        public int index_id { get; set; }
        public int partition_number { get; set; }
        public long hobt_id { get; set; }
        public long rows { get; set; }
        public short filestream_filegroup_id { get; set; }
        public byte data_compression { get; set; }
        public string data_compression_desc { get; set; }
    }
}
