//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysplan_guides
    {
        public int plan_guide_id { get; set; }
        public string name { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modify_date { get; set; }
        public bool is_disabled { get; set; }
        public string query_text { get; set; }
        public byte scope_type { get; set; }
        public string scope_type_desc { get; set; }
        public Nullable<int> scope_object_id { get; set; }
        public string scope_batch { get; set; }
        public string parameters { get; set; }
        public string hints { get; set; }
    }
}
