//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysspatial_indexes
    {
        public int object_id { get; set; }
        public string name { get; set; }
        public int index_id { get; set; }
        public byte type { get; set; }
        public string type_desc { get; set; }
        public Nullable<bool> is_unique { get; set; }
        public int data_space_id { get; set; }
        public Nullable<bool> ignore_dup_key { get; set; }
        public Nullable<bool> is_primary_key { get; set; }
        public Nullable<bool> is_unique_constraint { get; set; }
        public byte fill_factor { get; set; }
        public Nullable<bool> is_padded { get; set; }
        public Nullable<bool> is_disabled { get; set; }
        public Nullable<bool> is_hypothetical { get; set; }
        public Nullable<bool> allow_row_locks { get; set; }
        public Nullable<bool> allow_page_locks { get; set; }
        public int spatial_index_type { get; set; }
        public string spatial_index_type_desc { get; set; }
        public string tessellation_scheme { get; set; }
        public bool has_filter { get; set; }
        public string filter_definition { get; set; }
    }
}
