//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssyscomment
    {
        public int id { get; set; }
        public Nullable<short> number { get; set; }
        public short colid { get; set; }
        public short status { get; set; }
        public byte[] ctext { get; set; }
        public Nullable<short> texttype { get; set; }
        public Nullable<short> language { get; set; }
        public bool encrypted { get; set; }
        public bool compressed { get; set; }
        public string text { get; set; }
    }
}
