//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssyscursortable
    {
        public int cursor_handle { get; set; }
        public string table_owner { get; set; }
        public string table_name { get; set; }
        public short optimizer_hint { get; set; }
        public short lock_type { get; set; }
        public string server_name { get; set; }
        public int objectid { get; set; }
        public int dbid { get; set; }
        public string dbname { get; set; }
    }
}
