//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssyscolumn
    {
        public string name { get; set; }
        public int id { get; set; }
        public byte xtype { get; set; }
        public Nullable<byte> typestat { get; set; }
        public Nullable<short> xusertype { get; set; }
        public short length { get; set; }
        public byte xprec { get; set; }
        public byte xscale { get; set; }
        public Nullable<short> colid { get; set; }
        public Nullable<short> xoffset { get; set; }
        public Nullable<byte> bitpos { get; set; }
        public Nullable<byte> reserved { get; set; }
        public Nullable<short> colstat { get; set; }
        public int cdefault { get; set; }
        public int domain { get; set; }
        public Nullable<short> number { get; set; }
        public Nullable<short> colorder { get; set; }
        public byte[] autoval { get; set; }
        public Nullable<short> offset { get; set; }
        public int collationid { get; set; }
        public Nullable<int> language { get; set; }
        public Nullable<byte> status { get; set; }
        public byte type { get; set; }
        public Nullable<short> usertype { get; set; }
        public string printfmt { get; set; }
        public Nullable<short> prec { get; set; }
        public Nullable<int> scale { get; set; }
        public Nullable<int> iscomputed { get; set; }
        public Nullable<int> isoutparam { get; set; }
        public Nullable<int> isnullable { get; set; }
        public string collation { get; set; }
        public byte[] tdscollation { get; set; }
    }
}
