//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysserver_event_sessions
    {
        public int event_session_id { get; set; }
        public string name { get; set; }
        public string event_retention_mode { get; set; }
        public string event_retention_mode_desc { get; set; }
        public Nullable<int> max_dispatch_latency { get; set; }
        public Nullable<int> max_memory { get; set; }
        public Nullable<int> max_event_size { get; set; }
        public string memory_partition_mode { get; set; }
        public string memory_partition_mode_desc { get; set; }
        public Nullable<bool> track_causality { get; set; }
        public Nullable<bool> startup_state { get; set; }
    }
}
