//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssyslockinfo
    {
        public string rsc_text { get; set; }
        public byte[] rsc_bin { get; set; }
        public byte[] rsc_valblk { get; set; }
        public short rsc_dbid { get; set; }
        public short rsc_indid { get; set; }
        public int rsc_objid { get; set; }
        public byte rsc_type { get; set; }
        public byte rsc_flag { get; set; }
        public byte req_mode { get; set; }
        public byte req_status { get; set; }
        public short req_refcnt { get; set; }
        public short req_cryrefcnt { get; set; }
        public int req_lifetime { get; set; }
        public int req_spid { get; set; }
        public int req_ecid { get; set; }
        public short req_ownertype { get; set; }
        public Nullable<long> req_transactionID { get; set; }
        public Nullable<System.Guid> req_transactionUOW { get; set; }
    }
}
