//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssysobject
    {
        public string name { get; set; }
        public int id { get; set; }
        public string xtype { get; set; }
        public Nullable<short> uid { get; set; }
        public Nullable<short> info { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> base_schema_ver { get; set; }
        public Nullable<int> replinfo { get; set; }
        public int parent_obj { get; set; }
        public System.DateTime crdate { get; set; }
        public Nullable<short> ftcatid { get; set; }
        public Nullable<int> schema_ver { get; set; }
        public Nullable<int> stats_schema_ver { get; set; }
        public string type { get; set; }
        public Nullable<short> userstat { get; set; }
        public Nullable<short> sysstat { get; set; }
        public Nullable<short> indexdel { get; set; }
        public System.DateTime refdate { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<int> deltrig { get; set; }
        public Nullable<int> instrig { get; set; }
        public Nullable<int> updtrig { get; set; }
        public Nullable<int> seltrig { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<short> cache { get; set; }
    }
}
