//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssyscursor
    {
        public int cursor_handle { get; set; }
        public string cursor_name { get; set; }
        public int status { get; set; }
        public byte model { get; set; }
        public byte concurrency { get; set; }
        public byte scrollable { get; set; }
        public byte open_status { get; set; }
        public Nullable<decimal> cursor_rows { get; set; }
        public short fetch_status { get; set; }
        public short column_count { get; set; }
        public Nullable<decimal> row_count { get; set; }
        public byte last_operation { get; set; }
    }
}
