//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssyspermission
    {
        public int id { get; set; }
        public Nullable<short> grantee { get; set; }
        public Nullable<short> grantor { get; set; }
        public Nullable<short> actadd { get; set; }
        public Nullable<short> actmod { get; set; }
        public byte[] seladd { get; set; }
        public byte[] selmod { get; set; }
        public byte[] updadd { get; set; }
        public byte[] updmod { get; set; }
        public byte[] refadd { get; set; }
        public byte[] refmod { get; set; }
    }
}
