//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssystem_internals_partition_columns
    {
        public long partition_id { get; set; }
        public int partition_column_id { get; set; }
        public long modified_count { get; set; }
        public Nullable<short> max_inrow_length { get; set; }
        public Nullable<bool> is_replicated { get; set; }
        public Nullable<bool> is_logged_for_replication { get; set; }
        public Nullable<bool> is_dropped { get; set; }
        public Nullable<byte> system_type_id { get; set; }
        public Nullable<short> max_length { get; set; }
        public Nullable<byte> precision { get; set; }
        public Nullable<byte> scale { get; set; }
        public string collation_name { get; set; }
        public Nullable<bool> is_filestream { get; set; }
        public short key_ordinal { get; set; }
        public Nullable<bool> is_nullable { get; set; }
        public Nullable<bool> is_descending_key { get; set; }
        public Nullable<bool> is_uniqueifier { get; set; }
        public Nullable<short> leaf_offset { get; set; }
        public Nullable<short> internal_offset { get; set; }
        public Nullable<byte> leaf_bit_position { get; set; }
        public Nullable<byte> internal_bit_position { get; set; }
        public Nullable<short> leaf_null_bit { get; set; }
        public Nullable<short> internal_null_bit { get; set; }
        public Nullable<bool> is_anti_matter { get; set; }
        public Nullable<System.Guid> partition_column_guid { get; set; }
        public Nullable<bool> is_sparse { get; set; }
    }
}
