//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysserver_file_audits
    {
        public int audit_id { get; set; }
        public string name { get; set; }
        public Nullable<System.Guid> audit_guid { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modify_date { get; set; }
        public Nullable<int> principal_id { get; set; }
        public string type { get; set; }
        public string type_desc { get; set; }
        public Nullable<byte> on_failure { get; set; }
        public string on_failure_desc { get; set; }
        public Nullable<bool> is_state_enabled { get; set; }
        public Nullable<int> queue_delay { get; set; }
        public Nullable<long> max_file_size { get; set; }
        public Nullable<int> max_rollover_files { get; set; }
        public Nullable<bool> reserve_disk_space { get; set; }
        public string log_file_path { get; set; }
        public string log_file_name { get; set; }
    }
}
