//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssysuser
    {
        public Nullable<short> uid { get; set; }
        public Nullable<short> status { get; set; }
        public string name { get; set; }
        public byte[] sid { get; set; }
        public byte[] roles { get; set; }
        public System.DateTime createdate { get; set; }
        public System.DateTime updatedate { get; set; }
        public Nullable<short> altuid { get; set; }
        public byte[] password { get; set; }
        public Nullable<short> gid { get; set; }
        public string environ { get; set; }
        public Nullable<int> hasdbaccess { get; set; }
        public Nullable<int> islogin { get; set; }
        public Nullable<int> isntname { get; set; }
        public Nullable<int> isntgroup { get; set; }
        public Nullable<int> isntuser { get; set; }
        public Nullable<int> issqluser { get; set; }
        public Nullable<int> isaliased { get; set; }
        public Nullable<int> issqlrole { get; set; }
        public Nullable<int> isapprole { get; set; }
    }
}
