//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssysserver
    {
        public Nullable<short> srvid { get; set; }
        public Nullable<short> srvstatus { get; set; }
        public string srvname { get; set; }
        public string srvproduct { get; set; }
        public string providername { get; set; }
        public string datasource { get; set; }
        public string location { get; set; }
        public string providerstring { get; set; }
        public System.DateTime schemadate { get; set; }
        public Nullable<int> topologyx { get; set; }
        public Nullable<int> topologyy { get; set; }
        public string catalog { get; set; }
        public string srvcollation { get; set; }
        public Nullable<int> connecttimeout { get; set; }
        public Nullable<int> querytimeout { get; set; }
        public string srvnetname { get; set; }
        public Nullable<bool> isremote { get; set; }
        public bool rpc { get; set; }
        public bool pub { get; set; }
        public Nullable<bool> sub { get; set; }
        public Nullable<bool> dist { get; set; }
        public Nullable<bool> dpub { get; set; }
        public bool rpcout { get; set; }
        public bool dataaccess { get; set; }
        public bool collationcompatible { get; set; }
        public bool system { get; set; }
        public bool useremotecollation { get; set; }
        public bool lazyschemavalidation { get; set; }
        public string collation { get; set; }
        public Nullable<bool> nonsqlsub { get; set; }
    }
}
