//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssysindex
    {
        public int id { get; set; }
        public Nullable<int> status { get; set; }
        public byte[] first { get; set; }
        public Nullable<short> indid { get; set; }
        public byte[] root { get; set; }
        public Nullable<short> minlen { get; set; }
        public Nullable<short> keycnt { get; set; }
        public Nullable<short> groupid { get; set; }
        public Nullable<int> dpages { get; set; }
        public Nullable<int> reserved { get; set; }
        public Nullable<int> used { get; set; }
        public Nullable<long> rowcnt { get; set; }
        public Nullable<int> rowmodctr { get; set; }
        public Nullable<byte> reserved3 { get; set; }
        public Nullable<byte> reserved4 { get; set; }
        public Nullable<short> xmaxlen { get; set; }
        public Nullable<short> maxirow { get; set; }
        public Nullable<byte> OrigFillFactor { get; set; }
        public Nullable<byte> StatVersion { get; set; }
        public Nullable<int> reserved2 { get; set; }
        public byte[] FirstIAM { get; set; }
        public Nullable<short> impid { get; set; }
        public Nullable<short> lockflags { get; set; }
        public Nullable<int> pgmodctr { get; set; }
        public byte[] keys { get; set; }
        public string name { get; set; }
        public byte[] statblob { get; set; }
        public Nullable<int> maxlen { get; set; }
        public Nullable<int> rows { get; set; }
    }
}
