//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssoap_endpoints
    {
        public string name { get; set; }
        public int endpoint_id { get; set; }
        public Nullable<int> principal_id { get; set; }
        public byte protocol { get; set; }
        public string protocol_desc { get; set; }
        public byte type { get; set; }
        public string type_desc { get; set; }
        public Nullable<byte> state { get; set; }
        public string state_desc { get; set; }
        public bool is_admin_endpoint { get; set; }
        public bool is_sql_language_enabled { get; set; }
        public string wsdl_generator_procedure { get; set; }
        public string default_database { get; set; }
        public string default_namespace { get; set; }
        public Nullable<byte> default_result_schema { get; set; }
        public string default_result_schema_desc { get; set; }
        public bool is_xml_charset_enforced { get; set; }
        public bool is_session_enabled { get; set; }
        public int session_timeout { get; set; }
        public string login_type { get; set; }
        public int header_limit { get; set; }
    }
}
