//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysserver_trigger_events
    {
        public int object_id { get; set; }
        public int type { get; set; }
        public string type_desc { get; set; }
        public Nullable<bool> is_first { get; set; }
        public Nullable<bool> is_last { get; set; }
        public Nullable<int> event_group_type { get; set; }
        public string event_group_type_desc { get; set; }
    }
}
