//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssystem_components_surface_area_configuration
    {
        public string component_name { get; set; }
        public string database_name { get; set; }
        public string schema_name { get; set; }
        public string object_name { get; set; }
        public Nullable<byte> state { get; set; }
        public string type { get; set; }
        public string type_desc { get; set; }
    }
}
