//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssystem_internals_partitions
    {
        public long partition_id { get; set; }
        public int object_id { get; set; }
        public int index_id { get; set; }
        public int partition_number { get; set; }
        public long rows { get; set; }
        public short filestream_filegroup_id { get; set; }
        public Nullable<bool> is_orphaned { get; set; }
        public Nullable<byte> dropped_lob_column_state { get; set; }
        public Nullable<bool> is_unique { get; set; }
        public Nullable<bool> is_replicated { get; set; }
        public Nullable<bool> is_logged_for_replication { get; set; }
        public short max_null_bit_used { get; set; }
        public int max_leaf_length { get; set; }
        public short min_leaf_length { get; set; }
        public short max_internal_length { get; set; }
        public short min_internal_length { get; set; }
        public Nullable<bool> allows_nullable_keys { get; set; }
        public Nullable<bool> allow_row_locks { get; set; }
        public Nullable<bool> allow_page_locks { get; set; }
        public Nullable<bool> is_data_row_format { get; set; }
        public Nullable<bool> is_not_versioned { get; set; }
        public Nullable<System.Guid> filestream_guid { get; set; }
    }
}
