//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssysaltfile
    {
        public Nullable<short> fileid { get; set; }
        public Nullable<short> groupid { get; set; }
        public int size { get; set; }
        public int maxsize { get; set; }
        public int growth { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> perf { get; set; }
        public Nullable<short> dbid { get; set; }
        public string name { get; set; }
        public string filename { get; set; }
    }
}
