//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysserver
    {
        public int server_id { get; set; }
        public string name { get; set; }
        public string product { get; set; }
        public string provider { get; set; }
        public string data_source { get; set; }
        public string location { get; set; }
        public string provider_string { get; set; }
        public string catalog { get; set; }
        public Nullable<int> connect_timeout { get; set; }
        public Nullable<int> query_timeout { get; set; }
        public bool is_linked { get; set; }
        public bool is_remote_login_enabled { get; set; }
        public bool is_rpc_out_enabled { get; set; }
        public bool is_data_access_enabled { get; set; }
        public bool is_collation_compatible { get; set; }
        public bool uses_remote_collation { get; set; }
        public string collation_name { get; set; }
        public bool lazy_schema_validation { get; set; }
        public bool is_system { get; set; }
        public bool is_publisher { get; set; }
        public Nullable<bool> is_subscriber { get; set; }
        public Nullable<bool> is_distributor { get; set; }
        public Nullable<bool> is_nonsql_subscriber { get; set; }
        public Nullable<bool> is_remote_proc_transaction_promotion_enabled { get; set; }
        public System.DateTime modify_date { get; set; }
    }
}
