//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysspatial_index_tessellations
    {
        public int object_id { get; set; }
        public int index_id { get; set; }
        public string tessellation_scheme { get; set; }
        public Nullable<double> bounding_box_xmin { get; set; }
        public Nullable<double> bounding_box_ymin { get; set; }
        public Nullable<double> bounding_box_xmax { get; set; }
        public Nullable<double> bounding_box_ymax { get; set; }
        public Nullable<short> level_1_grid { get; set; }
        public string level_1_grid_desc { get; set; }
        public Nullable<short> level_2_grid { get; set; }
        public string level_2_grid_desc { get; set; }
        public Nullable<short> level_3_grid { get; set; }
        public string level_3_grid_desc { get; set; }
        public Nullable<short> level_4_grid { get; set; }
        public string level_4_grid_desc { get; set; }
        public Nullable<int> cells_per_object { get; set; }
    }
}
