//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssysreference
    {
        public int constid { get; set; }
        public int fkeyid { get; set; }
        public Nullable<int> rkeyid { get; set; }
        public Nullable<short> rkeyindid { get; set; }
        public Nullable<short> keycnt { get; set; }
        public byte[] forkeys { get; set; }
        public byte[] refkeys { get; set; }
        public Nullable<short> fkeydbid { get; set; }
        public Nullable<short> rkeydbid { get; set; }
        public Nullable<short> fkey1 { get; set; }
        public Nullable<short> fkey2 { get; set; }
        public Nullable<short> fkey3 { get; set; }
        public Nullable<short> fkey4 { get; set; }
        public Nullable<short> fkey5 { get; set; }
        public Nullable<short> fkey6 { get; set; }
        public Nullable<short> fkey7 { get; set; }
        public Nullable<short> fkey8 { get; set; }
        public Nullable<short> fkey9 { get; set; }
        public Nullable<short> fkey10 { get; set; }
        public Nullable<short> fkey11 { get; set; }
        public Nullable<short> fkey12 { get; set; }
        public Nullable<short> fkey13 { get; set; }
        public Nullable<short> fkey14 { get; set; }
        public Nullable<short> fkey15 { get; set; }
        public Nullable<short> fkey16 { get; set; }
        public Nullable<short> rkey1 { get; set; }
        public Nullable<short> rkey2 { get; set; }
        public Nullable<short> rkey3 { get; set; }
        public Nullable<short> rkey4 { get; set; }
        public Nullable<short> rkey5 { get; set; }
        public Nullable<short> rkey6 { get; set; }
        public Nullable<short> rkey7 { get; set; }
        public Nullable<short> rkey8 { get; set; }
        public Nullable<short> rkey9 { get; set; }
        public Nullable<short> rkey10 { get; set; }
        public Nullable<short> rkey11 { get; set; }
        public Nullable<short> rkey12 { get; set; }
        public Nullable<short> rkey13 { get; set; }
        public Nullable<short> rkey14 { get; set; }
        public Nullable<short> rkey15 { get; set; }
        public Nullable<short> rkey16 { get; set; }
    }
}
