//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssyscursorcolumn
    {
        public int cursor_handle { get; set; }
        public string column_name { get; set; }
        public int ordinal_position { get; set; }
        public int column_characteristics_flags { get; set; }
        public int column_size { get; set; }
        public int data_type_sql { get; set; }
        public byte column_precision { get; set; }
        public byte column_scale { get; set; }
        public int order_position { get; set; }
        public string order_direction { get; set; }
        public short hidden_column { get; set; }
        public int columnid { get; set; }
        public int objectid { get; set; }
        public int dbid { get; set; }
        public string dbname { get; set; }
    }
}
