//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssyslanguage
    {
        public short langid { get; set; }
        public string dateformat { get; set; }
        public byte datefirst { get; set; }
        public Nullable<int> upgrade { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public string months { get; set; }
        public string shortmonths { get; set; }
        public string days { get; set; }
        public int lcid { get; set; }
        public short msglangid { get; set; }
    }
}
