//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class systransmission_queue
    {
        public System.Guid conversation_handle { get; set; }
        public string to_service_name { get; set; }
        public string to_broker_instance { get; set; }
        public string from_service_name { get; set; }
        public string service_contract_name { get; set; }
        public System.DateTime enqueue_time { get; set; }
        public long message_sequence_number { get; set; }
        public string message_type_name { get; set; }
        public bool is_conversation_error { get; set; }
        public bool is_end_of_dialog { get; set; }
        public byte[] message_body { get; set; }
        public string transmission_status { get; set; }
        public byte priority { get; set; }
    }
}
