//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class systable
    {
        public string name { get; set; }
        public int object_id { get; set; }
        public Nullable<int> principal_id { get; set; }
        public int schema_id { get; set; }
        public int parent_object_id { get; set; }
        public string type { get; set; }
        public string type_desc { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modify_date { get; set; }
        public bool is_ms_shipped { get; set; }
        public bool is_published { get; set; }
        public bool is_schema_published { get; set; }
        public Nullable<int> lob_data_space_id { get; set; }
        public Nullable<int> filestream_data_space_id { get; set; }
        public int max_column_id_used { get; set; }
        public bool lock_on_bulk_load { get; set; }
        public Nullable<bool> uses_ansi_nulls { get; set; }
        public Nullable<bool> is_replicated { get; set; }
        public Nullable<bool> has_replication_filter { get; set; }
        public Nullable<bool> is_merge_published { get; set; }
        public Nullable<bool> is_sync_tran_subscribed { get; set; }
        public bool has_unchecked_assembly_data { get; set; }
        public Nullable<int> text_in_row_limit { get; set; }
        public Nullable<bool> large_value_types_out_of_row { get; set; }
        public Nullable<bool> is_tracked_by_cdc { get; set; }
        public Nullable<byte> lock_escalation { get; set; }
        public string lock_escalation_desc { get; set; }
    }
}
