//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class systrace
    {
        public int id { get; set; }
        public int status { get; set; }
        public string path { get; set; }
        public Nullable<long> max_size { get; set; }
        public Nullable<System.DateTime> stop_time { get; set; }
        public Nullable<int> max_files { get; set; }
        public Nullable<bool> is_rowset { get; set; }
        public Nullable<bool> is_rollover { get; set; }
        public Nullable<bool> is_shutdown { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<int> buffer_count { get; set; }
        public Nullable<int> buffer_size { get; set; }
        public Nullable<long> file_position { get; set; }
        public Nullable<int> reader_spid { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> last_event_time { get; set; }
        public Nullable<long> event_count { get; set; }
        public Nullable<int> dropped_event_count { get; set; }
    }
}
