//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class systrigger
    {
        public string name { get; set; }
        public int object_id { get; set; }
        public byte parent_class { get; set; }
        public string parent_class_desc { get; set; }
        public int parent_id { get; set; }
        public string type { get; set; }
        public string type_desc { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modify_date { get; set; }
        public bool is_ms_shipped { get; set; }
        public bool is_disabled { get; set; }
        public bool is_not_for_replication { get; set; }
        public bool is_instead_of_trigger { get; set; }
    }
}
