//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysxml_schema_attributes
    {
        public int xml_component_id { get; set; }
        public int xml_collection_id { get; set; }
        public int xml_namespace_id { get; set; }
        public bool is_qualified { get; set; }
        public string name { get; set; }
        public string symbol_space { get; set; }
        public string symbol_space_desc { get; set; }
        public string kind { get; set; }
        public string kind_desc { get; set; }
        public string derivation { get; set; }
        public string derivation_desc { get; set; }
        public Nullable<int> base_xml_component_id { get; set; }
        public Nullable<int> scoping_xml_component_id { get; set; }
        public bool is_default_fixed { get; set; }
        public bool must_be_qualified { get; set; }
        public string default_value { get; set; }
    }
}
