//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int 車次 { get; set; }
        public string 車種 { get; set; }
        public string 起站 { get; set; }
        public string 終站 { get; set; }
        public int 開車時間 { get; set; }
        public int 到站時間 { get; set; }
        public string 經過站名 { get; set; }
    }
}
