//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEstCompareReal
    {
        public string 資料類別 { get; set; }
        public string 員工編號姓名 { get; set; }
        public Nullable<int> 預估_實際工作起始日_年度_ { get; set; }
        public Nullable<int> 預估_實際工作起始日_月份_ { get; set; }
        public Nullable<System.DateTime> 預估_實際工作起始日 { get; set; }
        public Nullable<int> 預估_實際工作截止日_年度_ { get; set; }
        public Nullable<int> 預估_實際工作截止日_月份_ { get; set; }
        public Nullable<System.DateTime> 預估_實際工作截止日 { get; set; }
        public string 項目代碼名稱 { get; set; }
        public string 第一階作業 { get; set; }
        public string 第二階作業 { get; set; }
        public string 第三階作業 { get; set; }
        public string 第四階作業 { get; set; }
        public Nullable<decimal> 預估時數 { get; set; }
        public Nullable<decimal> 實際時數 { get; set; }
    }
}
