//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwModelDataProject
    {
        public string 項目代碼 { get; set; }
        public string 項目名稱 { get; set; }
        public string 部門代碼 { get; set; }
        public string 部門名稱 { get; set; }
        public string 項目負責人姓名 { get; set; }
        public Nullable<System.DateTime> 項目起日 { get; set; }
        public Nullable<System.DateTime> 項目迄日 { get; set; }
    }
}
