//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPeriodDataActualCapacity
    {
        public string 部門代碼 { get; set; }
        public string 部門名稱 { get; set; }
        public string 員工編號 { get; set; }
        public string 員工姓名 { get; set; }
        public string 第1階作業代碼 { get; set; }
        public string 第1階作業名稱 { get; set; }
        public string 第2階作業代碼 { get; set; }
        public string 第2階作業名稱 { get; set; }
        public string 第3階作業代碼 { get; set; }
        public string 第3階作業名稱 { get; set; }
        public string 第4階作業代碼 { get; set; }
        public string 第4階作業名稱 { get; set; }
        public decimal 實際工時 { get; set; }
        public string 內部修改原因 { get; set; }
        public string 項目代碼 { get; set; }
        public string 項目名稱 { get; set; }
        public string 作業描述 { get; set; }
        public Nullable<int> 實際工作日_年 { get; set; }
        public Nullable<int> 實際工作日_月 { get; set; }
        public Nullable<int> 實際工作日_日 { get; set; }
        public System.DateTime 實際工作日 { get; set; }
    }
}
