//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSampleCompareWorkData
    {
        public string 員工編號 { get; set; }
        public string 員工姓名 { get; set; }
        public string TaskName { get; set; }
        public string 第一階作業 { get; set; }
        public string 第二階作業 { get; set; }
        public string 第三階作業 { get; set; }
        public string 第四階作業 { get; set; }
        public string 項目名稱 { get; set; }
        public string 作業名稱 { get; set; }
        public Nullable<int> 工作年度 { get; set; }
        public Nullable<int> 工作月份 { get; set; }
        public Nullable<System.DateTime> 工作日期 { get; set; }
        public Nullable<decimal> 預估工時 { get; set; }
        public decimal 實際工時 { get; set; }
        public Nullable<System.DateTime> CalSDate { get; set; }
        public Nullable<System.DateTime> CalEDate { get; set; }
    }
}
