//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSampleFroecastData
    {
        public System.Guid EmpID { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> CalSDate { get; set; }
        public Nullable<System.DateTime> CalEDate { get; set; }
        public System.Guid TaskID { get; set; }
        public string TaskName { get; set; }
        public System.Guid ProcID { get; set; }
        public string PIDs { get; set; }
        public string PID { get; set; }
        public string LV1 { get; set; }
        public string LV2 { get; set; }
        public string LV3 { get; set; }
        public string LV4 { get; set; }
        public decimal CalHours { get; set; }
        public string EmpNo { get; set; }
    }
}
