//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0805.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowProcessScheme
    {
        public System.Guid Id { get; set; }
        public string Scheme { get; set; }
        public string DefiningParameters { get; set; }
        public string DefiningParametersHash { get; set; }
        public string SchemeCode { get; set; }
        public bool IsObsolete { get; set; }
        public string RootSchemeCode { get; set; }
        public Nullable<System.Guid> RootSchemeId { get; set; }
        public string AllowedActivities { get; set; }
        public string StartingTransition { get; set; }
    }
}
